### ISSUE TITLE
The "Give up" option on a mod's game over screen causes the level to restart anyways.

### ISSUE THREAD

**Issue by Ozrenol** [bunfan/beat-banger-public#10]
**Bug description**
Regardless of keybind, pressing the "give up" button on a mod's game over screen will be the same as trying again, the sfx for both options will play simultaneously as well.

**To Reproduce**
1. Play any mod level;
2. Fail;
3. Press the Secondary Key/Note 2 key to give up;
4. Restart the level anyways.

**Expected behavior**
I expected to go back to the level selection screen.

**Screenshots**
Due to the nature of the bug, I had to take a video with my phone instead

https://github.com/bunfan/beat-banger-public/assets/134641266/e3e8455b-f9e4-45af-9208-63e2df6e6f38

**Desktop:**
 -  Windows 11
 - Version 2.892

**Comment by komdog** [comment]
Fixed and will be pushed soon
