### ISSUE TITLE
Sound/Screen effect when missing a key

### ISSUE THREAD

**Issue by Unrequited-jpg** [bunfan/beat-banger-public#10]
Hi Kom, sorry if this is covered by 'Organic Screen FX' on your roadmap, but I found that missing a key wasn't represented by any sort of feedback - would help to reinforce a miss with more obvious feedback for the player.

**Comment by komdog** [comment]
There's already a sound that played and a note color change when you miss one, but I'll probably make that sound more noticeable in the future.
