### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by gazul5** [bunfan/beat-banger-public#100]
### Discord Tag

gazul

### What happened?

the game crashed soon as i beat the second level on virgin (perfect score)
the instruction at 0x00007FF6D3568234 referenced memory at 0xFFFFFFFFFFFFFFFF, the memory could not be read.

### OS

Windows

### Version

3.165 (Secret)

**Comment by Stefan-Mitric** [comment]
Can you provide the beatbanger.log file?

**Comment by Stefan-Mitric** [comment]
Claire Level Crashing #84

**Comment by gazul5** [comment]
> Could you please send me the 'beatbanger.log' file? Thanks!

sorry i didn't know how to do that at the time, and i had already gone to bed. but once i reopened the game the 3rd level was unlocked and i just kept playing and had no other problems.

**Comment by komdog** [comment]
Dupe of fixed issue #84
