### ISSUE TITLE
Tate mode

### ISSUE THREAD

**Issue by BraixenFan** [bunfan/beat-banger-public#100]
**What feature would you like to request?:**
I suggest a Tate mode should be added as an option in the options menu, since the game is played in a vertical screen I think it would fit quite well and allow the game to be played full-screen without any letterboxing

**Additional context**
Tate mode is an option from vertical Shoot 'em ups to render the game sideways, once active, the user is then supposed to tilt their screen to match the new orientation, [Here's an image I found of this in action](https://i.imgur.com/4EtP0n3.jpg), it usually has two options, Left and right, which of course rotates the screen either 90° or 270°

**Comment by theGrames** [comment]
Game has been converted to 16:9. We are looking into backwards compatibility for older, vertical animation mods.
