### ISSUE TITLE
Patch Notes Don't Scroll

### ISSUE THREAD

**Issue by DjBRINE** [bunfan/beat-banger-public#104]
### Discord Tag

@djbrine1

### What happened?

When looking at Patch Notes in the secret Claire beta, i cannot scroll a Patch Notes list
I expected to be able to scroll it with arrow keys, or Pg Up & Pg Dn, or W & S, or with a scroll wheel, or by dragging the vertical bar on the left

### OS

Linux

### Version

3.165 (Secret)

**Comment by komdog** [comment]
Moved to #107
