### ISSUE TITLE
The hud toggle feature doesnt work

### ISSUE THREAD

**Issue by Bohnsaw909** [bunfan/beat-banger-public#109]
### Discord Tag

@Bohnsaw/Disord Nerd

### Issue Description

bought the hud toggle from the shop and on or off the hud still shows on every song

### OS

Windows

### Version

3.165 (Secret)

**Comment by Bohnsaw909** [comment]
did one but forgot to add discord tag so i redid

**Comment by komdog** [comment]
It works on my end. Could you show screenshots or a video of this happening?

**Comment by Bohnsaw909** [comment]
https://clipchamp.com/watch/elOh1GUvPoE

**Comment by komdog** [comment]
The beat bar is not included in the hud
