### ISSUE TITLE
How about the player gets beat-banged?

### ISSUE THREAD

**Issue by CrashBurger** [bunfan/beat-banger-public#11]
I'm not a patron, but I hope you'll consider my request all the same! I've been following your game and am anticipating a public release to try out for myself. In the meantime, I had an idea. How about an animation from the POV of someone on the receiving end? So - you're the one receiving the schmeat to the music?

It's probably not in line with your vision so far, but it might be unique enough to interest you? I'm possibly in the minority of wanting be dicked-down, so perhaps a poll among your patrons would be best to see what they prefer. Keep up the good work, and thanks!

**Comment by komdog** [comment]
Thanks for your suggestion. However, we're currently not planning on adding any new characters until the required Patreon goal is met.
