### ISSUE TITLE
[ Secret ] Cathy Bug 

### ISSUE THREAD

**Issue by CrimsonRUL3** [bunfan/beat-banger-public#110]
### Discord Tag

@the_crimson_rul3

### Issue Description

When playing through Cathy Normal difficulty, the animations vanished after the pussy licking scene.

Following this, all difficulties have the following pattern. ( Cathy Only )
No starting animations.
Blowjob and licking animations present.
And no final animations.

### OS

Windows

### Version

3.165 (Secret)

**Comment by Stefan-Mitric** [comment]
Could you please create a video for us? It would greatly help in better understanding the process and validating the results. Thank you!

**Comment by CrimsonRUL3** [comment]
Here's a recording of the Easy level.

**Comment by DoodleSurf** [comment]
Fixed in 3.22, please update to a relevant version.
