### ISSUE TITLE
Mod Bug: Freezing

### ISSUE THREAD

**Issue by JackMoon19** [bunfan/beat-banger-public#111]
### Discord Tag

@joaquinluna18

### Issue Description

When I play this mod, the level doesn't play. It just stays still.

https://github.com/bunfan/beat-banger-public/assets/148704925/66d67ea3-fc61-473a-94bf-0b9b72e03951

### OS

Windows

### Version

3.22 (Secret)

**Comment by DoodleSurf** [comment]
Can you provide a log file? Possibly the mod itself is bugged.

**Comment by Stefan-Mitric** [comment]
@DoodleSurf I've tried every Pikachu-related mod, but it hasn't happened for me. I've encountered this bug in the past but could never reproduce it. It happens very rarely.

**Comment by Stefan-Mitric** [comment]
Issue Identified: Mod Poorly Configured (and it was converted to release with Azzurra's Mod Converter).

**Comment by DoodleSurf** [comment]
Closed.
