### ISSUE TITLE
Level Editor: Vertical Lines Fail to Switch to Correct Indicator

### ISSUE THREAD

**Issue by Stefan-Mitric** [bunfan/beat-banger-public#112]
### Issue Description

1. Upon switching to the level editor, the incorrect line beat indicator is displayed; it defaults to the 1/4 beat indicator instead of the expected one (Beat).
2. As demonstrated in the video, it incorrectly switches to the 1/8 beat indicator rather than the intended 1/4 beat indicator.

https://github.com/bunfan/beat-banger-public/assets/146543675/1c728940-29bd-4e8f-9557-f9cb33efed76

### OS

Windows

### Version

3.22 (Secret)

**Comment by 1MPexe** [comment]
I've figured out the issue. Apparently it is all of the buttons. Clicking beat have it return to 1/2 when the level editor is reopened, and click 1/2 will have it return to 1/4 when reopened and so on. Some value in the code is returning either 1 more or 1 less than it actually needs on the beat snap drop down.

**Comment by komdog** [comment]
Fixed in 3.5
