### ISSUE TITLE
Level Editor: Images/Animations Protruding into TimeLineInfo Panel

### ISSUE THREAD

**Issue by Stefan-Mitric** [bunfan/beat-banger-public#113]
### Issue Description

I have identified a bug where, on some Mods, the images and animations are incorrectly extending beyond their designated areas, intruding into the TimeLineInfo Panel or even more into the editor.

![image](https://github.com/bunfan/beat-banger-public/assets/146543675/2645f402-183c-494e-813f-bd3bfafba669)

### OS

Windows

### Version

3.22 (Secret)

**Comment by komdog** [comment]
Fixed in 3.5
