### ISSUE TITLE
Crashes when changing resolution

### ISSUE THREAD

**Issue by Laymat123** [bunfan/beat-banger-public#115]
### Discord Tag

@gronkulator

### Issue Description

Changing resolution (any resolution) seems to crash the game.
(cant find where the version is, but its the one that just recently released (october 24th 2023))

https://github.com/bunfan/beat-banger-public/assets/148924229/47f0d992-6004-4b8b-8261-ec5735781cfa

### OS

Windows

### Version

3.22 (Secret)

**Comment by DoodleSurf** [comment]
Can you please provide the crash log file? It is located in the following folder:
`C:\Users\Username\AppData\Roaming\Godot\app_userdata\Beat Banger\logs`

**Comment by Stefan-Mitric** [comment]
could you find the following folder:
C:\Users\Username\AppData\Roaming\Godot\app_userdata\Beat Banger\logs

**Comment by 1MPexe** [comment]
I can't reproduce the bug. It seems to be fixed in the latest version.
