### ISSUE TITLE
Bug: Unable to change resolution and aspect ratio

### ISSUE THREAD

**Issue by Travag** [bunfan/beat-banger-public#116]
### Discord Tag

Pelli03

### Issue Description

When I go into the settings, I am unable to change the resolution of my game. While all the other settings are colored in their normal orange color, the aspect ratio is greyed out and are unable to be changed
![image](https://github.com/bunfan/beat-banger-public/assets/148924735/07868185-ceb7-469d-8988-17d9463ef901)

(I do not know the patch number but this is of the new release on 10/24/2023)
### OS

Windows

### Version

3.22 (Secret)

**Comment by DoodleSurf** [comment]
Limit the user's choice in resolution and ratio setting while the full screen mode being active is an intended behaviour since the engine maxes out resolution and ratio anyway. If you wish to change those options - make sure the game is set in a windowed mode.
