### ISSUE TITLE
Bug: Lag

### ISSUE THREAD

**Issue by LustDemon** [bunfan/beat-banger-public#118]
### Discord Tag

@RogueofLust

### Issue Description

It's not really a bug, but now the game is insanely laggy at the point that I can't play any level. I have tried to go to settings to see if that could solve the problem but nothing there could help at all with this lag I really hope for a better optimization for the next update of the game or else me and other people that doesn't have a potent pc can't play the game anymore. ( Until the recent update my game was really smooth and without any lags ). Thank you

### OS

Windows

### Version

3.22 (Secret)

**Comment by DoodleSurf** [comment]
Can you please provide your hardware specs?

**Comment by LustDemon** [comment]
> Can you please provide your hardware specs?
![Illustration2](https://github.com/bunfan/beat-banger-public/assets/87587624/4c2032fa-eab0-4482-bd14-d63db4542e6c)

**Comment by Stefan-Mitric** [comment]
Which Windows Version do you use? 7 or 10

**Comment by 1MPexe** [comment]
Is this issue still occurring?

**Comment by 1MPexe** [comment]
No further information provided.
