### ISSUE TITLE
Error in Post-Zoe cutscene script

### ISSUE THREAD

**Issue by monty8466** [bunfan/beat-banger-public#12]
**Describe the bug**
One of Claire's lines in the Zoe cutscene, "His last tangle with Zoe is going to be a hit!", is incorrectly labelled as Gale in the script.

**To Reproduce**
Play the Post-Zoe cutscene

**Expected behavior**
The above line should be labelled as Claire 

**Screenshots**
Line 115 of the script.cfg
`{		
"character" : "Gale",		
"src" : "18.png", 		
"dialogue" : "His last tangle with Zoe is going to be a hit!",		
"audio": ["claire_line (8).mp3"],	
},`

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Gale patreon test build
 
**Additional context**
-

**Comment by komdog** [comment]
This has been fixed and will be pushed next public update! Thank you for reporting!
