### ISSUE TITLE
New update lost all my progress.

### ISSUE THREAD

**Issue by Sandwitcher03** [bunfan/beat-banger-public#120]
### Discord Tag

@werewolffucker

### Issue Description

When I downloaded the newest update and opened the game, everything was locked. I had every extra unlocked, every level, so far, beat. Now all my progress is gone. Version is 3.3 btw.

### OS

Windows

### Version

3.22 (Secret)

**Comment by DoodleSurf** [comment]
The engine rewrite changed the internal save structure, unfortunately there is no way to transfer the progress from 2.92
