### ISSUE TITLE
Hands Free doesn't store menu cache

### ISSUE THREAD

**Issue by Yungdeag** [bunfan/beat-banger-public#124]
### Issue Description

The Claire Expert hands free doesn't seem to be expert, looks as if its playing the normal chart instead, only has a max score of 27000 so it may even be the easy chart.

### OS

Windows

### Version

3.3

**Comment by Stefan-Mitric** [comment]
So when you play the normal difficulty and try other Level Difficulty on hand free, it selects the normal difficulty instead of the right one you choose. Confirmed

**Comment by DoodleSurf** [comment]
Fixed in 3.31
