### ISSUE TITLE
Cathy level on mac not working

### ISSUE THREAD

**Issue by loseinto** [bunfan/beat-banger-public#127]
### Discord Tag

KyroNaught

### Issue Description

Halfway in to cathys level on mac the game freezes and forces me to force quit the game.

### OS

MacOS

### Version

3.3

**Comment by DoodleSurf** [comment]
@loseinto can you please provde the log file after the crash?
You can find it by following this path: `~/Library/Application Support/Godot/logs`

**Comment by Stefan-Mitric** [comment]
Could you find the following path:~/Library/Application Support/Godot/logs

**Comment by 1MPexe** [comment]
Is this issue still occurring?

**Comment by 1MPexe** [comment]
Not enough information provided after a long period of time.
