### ISSUE TITLE
Cutscenes not affected by volume settings

### ISSUE THREAD

**Issue by Stefan-Mitric** [bunfan/beat-banger-public#128]
### Issue Description

Voice Volume: This setting does not affect the cutscenes, even on 0% volume.

SFX Volume: This setting does not affect the cutscenes, even on 0% volume.

Music Volume: This setting is not properly functioning in the levels. When the slider is on 0%, the music is not gone, just slightly quieter, and does not affect the cutscenes, even on 0% volume.

### OS

Windows

### Version

3.3

**Comment by 1MPexe** [comment]
This bug has been fixed in our most recent update.
