### ISSUE TITLE
Game won't start on Windows

### ISSUE THREAD

**Issue by Voltkraken42** [bunfan/beat-banger-public#13]
**Describe the bug**
The game won't open. The Godot Engine app comes up in the Task Manager window for like a split second then immediately disappears when double-clicking on the app. It's even worse when trying to launch it from Steam because it doesn't come up at all.

**To Reproduce**
1. Try to run the app at all. Like, in any way.

**Expected behavior**
I expected the app to open and some sort of window to come up.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (via Bootcamp)
 - Version 22H2

**Additional context**

**Comment by komdog** [comment]
Hopefully this won't happen anymore as we push out the new engine update.
