### ISSUE TITLE
Doesnt launch the game

### ISSUE THREAD

**Issue by shark0boy22** [bunfan/beat-banger-public#134]
### Discord Tag

shark0boy

### Issue Description

before Claire update the game start everytime but now the game doesn't start anymore shame because i love this game so much.
my pc.
Yes i use the  steam version is this a permaproblem i can buy from Itch.io

i love your work if i had more money i sub your Patreon but sadly i work for Burger King XD.
.

### OS

Windows

### Version

3.3

**Comment by 1MPexe** [comment]
Is this issue still occurring?

**Comment by shark0boy22** [comment]
the problem still persist.
The problem is the C:\Users\username\AppData\Roaming\Godot\app_userdata\Beat Banger\logs vanish from my folder even if i reinstall the game dont come back. i try to install in one other pc and work fine but my old pc dont go

**Comment by shark0boy22** [comment]
Godot Engine v3.5.stable.custom_build.991bb6ac7 - https://godotengine.org
OpenGL ES 3.0 Renderer: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
Async. shader compilation: OFF
 
ERROR:  does not have a library for the current platform.
   at: NativeScriptLanguage::init_library (modules\gdnative\nativescript\nativescript.cpp:1479) - Condition "lib_path.length() == 0" is true.
[STEAM] Did Steam initialize?: {status:20, verbal:Steam not running.}
[STEAM] Failed to initialize Steam. Steam not running. Shutting down...
Loading User Settings...
Loaded Save File
(21:48:30) Loading Metadata and Sorting Levels...
(21:48:30) OS Name : Windows
(21:48:30) Game Version : 2.69
Saving user settings...

**Comment by DoodleSurf** [comment]
Your Game Version says `2.69`, you sure you are running the latest version or it could be an old log file from an old version of the game.

**Comment by shark0boy22** [comment]
my last log is this because i try the beta but the verrsion of steam 3.3.0 was deleted and never return even after i reinstall

**Comment by DoodleSurf** [comment]
are you sure you've disabled the beta branch in game's properties?

**Comment by shark0boy22** [comment]
pretty sure is not said anything about beta. 
that beta i install on discord but didnt know was  it before now.

**Comment by DoodleSurf** [comment]
can you plesase check it here?
![image](https://github.com/bunfan/beat-banger-public/assets/133990496/60908177-1b4f-458b-8b50-b8987499edb3)

**Comment by DoodleSurf** [comment]
Also be aware that logs have a different name. It's `beatbanger.log`, not `beat_banger.log`

**Comment by shark0boy22** [comment]
![Cattura](https://github.com/bunfan/beat-banger-public/assets/149097869/df928180-7a80-47d7-af21-98b7ba16615a)

this time i delete the logs reinstall the game but the godot folder isnt there

**Comment by DoodleSurf** [comment]
Can you screenshot the appdata folder?

**Comment by DoodleSurf** [comment]
wait why did you delete the logs

**Comment by DoodleSurf** [comment]
Issue resolved.
User had Steelseries Nahimic installed on his PC, which interfered with Godot initialization, which is a known issue.

Disabling this program - solved the problem.
![image](https://github.com/bunfan/beat-banger-public/assets/133990496/0142b43b-af87-4474-bdfb-5536b62d8930)
