### ISSUE TITLE
freezing mods

### ISSUE THREAD

**Issue by Gothvagabond** [bunfan/beat-banger-public#136]
### Discord Tag

TheGothVagabond

### Issue Description

certain mods freeze. to the point they do not play. some work some don't i do not know why is it something i have to fix?

### OS

Windows

### Version

3.3

**Comment by DoodleSurf** [comment]
@Gothvagabond 
Many mods were created using a bugged version of Azzura's Mod Converter. You can check for a potential fix by opening a `keyframes.cfg` of a mod and locating a field called `mc.BPM`. Its supposed to be named `bpm` instead.

If in doubt or you aren't able to locate the issue - provide a list of mods in question for further investigation.

**Comment by komdog** [comment]
If there's an issue with a mod, consider talking to the mod's creator, as we cannot fix user-generated content.
