### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Froopysmthng** [bunfan/beat-banger-public#137]
### Discord Tag

_froopy_

### Issue Description

IT RESET ALL OF MY PROGRESS!!!

### OS

Windows

### Version

3.3

### Relevant log output

```shell
what
```

**Comment by Froopysmthng** [comment]
hi

**Comment by DoodleSurf** [comment]
Migration of an engine changed the internal save structure - forcing the user to reset their progress. We are extremely for the inconvenience.
If you wish to skip some of the levels, you can always use a `dev` command in the F2 console and then pressing the `End` key on your keyboard during a level playthrough.
