### ISSUE TITLE
Can't go into windowed mode on Mac

### ISSUE THREAD

**Issue by Voltkraken42** [bunfan/beat-banger-public#14]
**Describe the bug**
When I try to change the screen mode, nothing happens and the screen just goes black/dark gray. I can still 

**To Reproduce**
1. Run the game
2. Go to the options menu
3. Go to the Screen Mode setting
4. Try changing that setting
5. See the error

**Expected behavior**
I'd expect the screen mode to change.

**Screenshots**
<img width="2560" alt="Screen Shot 2023-06-07 at 1 12 42 PM" src="https://github.com/bunfan/beat-banger-public/assets/9520758/316832bb-34e0-4737-990c-3434940df8f9">

**Desktop (please complete the following information):**
 - OS: Mac OS Big Sur
 - Version 11.7.7

**Additional context**
This is the version I downloaded from Steam.

**Comment by komdog** [comment]
This has been fixed and will be pushed soon <3
