### ISSUE TITLE
Beat Banging Kom (Kure x Kom)

### ISSUE THREAD

**Issue by Kuriepenguin** [bunfan/beat-banger-public#14]
I definitely support the idea of kom getting his  banged (Or him banging others) with other peoples characters for future ref. I definitely consider my OC kure at that. Just kom blowing him or getting his fat ass pegged is fine as i don't think other peoples OC's need to be fully seen. Kom would be the main attraction after all.

**Comment by MarukiSO** [comment]
Thank you for your suggestion. We don't have plans to add anymore characters till further noticed.
