### ISSUE TITLE
Mod Titles Extend Past Cover

### ISSUE THREAD

**Issue by Newcrominus** [bunfan/beat-banger-public#141]
### Issue Description

![image](https://github.com/bunfan/beat-banger-public/assets/107784806/2ec48137-2fcf-45ac-a420-6fa1e6813570)

And another tangentially related issue once inside the mod act
![image](https://github.com/bunfan/beat-banger-public/assets/107784806/04b148a7-56b7-4e23-a0c1-94b830d4da8f)

### OS

Windows

### Version

3.3

**Comment by 1MPexe** [comment]
This issue will be fixed in the next update.
