### ISSUE TITLE
Bug: Mods dont have hands free play

### ISSUE THREAD

**Issue by slxjo** [bunfan/beat-banger-public#142]
### Discord Tag

@slojo.

### Issue Description

After you complete a mod you cant access it with hand free play like you used to before the Claire update.

### OS

Windows

### Version

3.3

**Comment by Stefan-Mitric** [comment]
Could you make a video?

**Comment by slxjo** [comment]
https://github.com/bunfan/beat-banger-public/assets/129123979/1ae369cf-5654-4d0e-8e8a-d98d49caa568

I did it on expert and once you complete it, it doesn't show the option to play hands free. I even pressed 'V' a couple times to be sure.

**Comment by Stefan-Mitric** [comment]
Did you have the no Fail modifier on? If yes. with no fail, you can't progress. disable it and try it again.

**Comment by slxjo** [comment]
oh yea thats why, thanks!

**Comment by Stefan-Mitric** [comment]
Had No Fail on
