### ISSUE TITLE
ultimc mods

### ISSUE THREAD

**Issue by hassanhassandd** [bunfan/beat-banger-public#143]
### Discord Tag

hassanh #8836

### Issue Description

I have downloaded some mods in ultimc but when I enter into them the screen still on the log page, whats the problem solve?

### OS

Windows

### Version

3.3

**Comment by Stefan-Mitric** [comment]
Can you be more precise with the problem? What is ultimc?

**Comment by hassanhassandd** [comment]
Sorry, I mean multi mc


في السبت، ٢٨ أكتوبر ٢٠٢٣, ١٢:٢٨ ص Stefan ***@***.***> كتب:

**Comment by Stefan-Mitric** [comment]
Do you mean MultiMC  the alternative launcher for Minecraft?

**Comment by hassanhassandd** [comment]
Yes I have downloaded multi Mc (minecraft launcher) but when I download
mods they don't work


في السبت، ٢٨ أكتوبر ٢٠٢٣, ٣:٥٤ م Stefan ***@***.***> كتب:

**Comment by Stefan-Mitric** [comment]
Can you provide the right discord name? I can't find you on the Beat Banger discord server.

**Comment by hassanhassandd** [comment]
It's haassanh#8836

في السبت، ٢٨ أكتوبر ٢٠٢٣, ٤:٠٠ م Stefan ***@***.***> كتب:

**Comment by Stefan-Mitric** [comment]
He said it was a Minecraft mod. it was somehow redirected to our GitHub website. I'm just trying to figure out, how he found it and where he found it. Communicate with me via Discord.
