### ISSUE TITLE
Background Texture flashing bug?

### ISSUE THREAD

**Issue by Jax-Drades** [bunfan/beat-banger-public#145]
### Discord Tag

@Jax Drades

### Issue Description

Whenever hitting a note properly, the background texture will uniformly flash a lighter version of the texture, the characters themselves and the HUD are not affected.
Not sure if this counts as a bug but I found it to be somewhat distracting while going for highscores.
Have a good day. 
:D

### OS

Windows

### Version

3.3

**Comment by Stefan-Mitric** [comment]
Could you please provide a video?

**Comment by 1MPexe** [comment]
This is an intended feature. In the future, we may add accessibility options that will allow you to disable this feature.
