### ISSUE TITLE
Issue With Stars in E. Claire's Level

### ISSUE THREAD

**Issue by Moonluan** [bunfan/beat-banger-public#148]
### Discord Tag

mitsukimidnightpendragon

### Issue Description

well, i was playing my now favorite level of Beat Banger (i adored Claire BTW) when i managed to get the 7 star ratio in the expert score, but now when i entered tonight in the game again, the expert score didn't show the red ribbon, and then i just got it again, but when i got the 7 stars this time, the game crashed and kicked me out, what i could notice before it kicked me out, is that the score was somehow lower in the 7 stars even when almost 98% of the track was pure perfect and the rest was great notes, as if in the 6 stars score that i managed to pull was around the 28k, when the 7stars that i scored now was in 27k more or less

### OS

Windows

### Version

3.3

**Comment by 1MPexe** [comment]
Has this issue recently occurred more than once?

**Comment by Moonluan** [comment]
Yea, in fact, when i tried the other levels, i've kinda discovered the
issue in general, as i see it, the game needs to update the highscore of
any beat, and the problem is that what happens when the new highscore has
less quality (number of stars) than the previous one, as an example, when
an old highscore has 7 stars and is updated, but the new one somehow has 6
stars, the update launches an error that bails the player out of the game

**Comment by 1MPexe** [comment]
I can't seem to reproduce this bug. Could you provide video of the bug taking place?

**Comment by Moonluan** [comment]
Right now i cannot i am on the job, plus it would be difficult right now
since i have all of the levels at almost max score, with 7 stars and above
29k in all levels of difficulty

**Comment by 1MPexe** [comment]
Provide a video whenever you are able.

**Comment by 1MPexe** [comment]
Cannot reproduce bug.
