### ISSUE TITLE
Progress Locked

### ISSUE THREAD

**Issue by icarus-fallen** [bunfan/beat-banger-public#149]
### Discord Tag

icarus_1185

### Issue Description

I just completed the first level on virgin and it played the win screen. I was then sent back to the level selection screen. The next level was still locked. I checked the level I just did and there was no score or stars on it despite me not missing a single note. I restarted the game, with no changes to the score or star count. I tried again, this time on expert and beat it again. The same exact thing happened.

### OS

Windows

### Version

3.3

**Comment by Stefan-Mitric** [comment]
Did you have the no Fail modifier on? If yes. with no fail, you can't progress. disable it and try it again.

**Comment by 1MPexe** [comment]
No further information was provided.
