### ISSUE TITLE
Stacked Note on Gale level

### ISSUE THREAD

**Issue by JustKinda** [bunfan/beat-banger-public#15]
**Describe the bug**
In Gale's level, on Virgin difficulty, there are two notes stacked on top of each other.

**To Reproduce**
1. Enter the Gale level on Virgin difficulty
2. Play through the song normally
3. At about 26 seconds, hitting one of the notes will seem to not immediately clear it, causing a miss unless one double-taps quickly enough

**Expected behavior**
Ideally, hitting a note should cause the note to clear, instead of revealing a second identical note underneath it.

**Screenshots**
![Screenshot_3](https://github.com/bunfan/beat-banger-public/assets/87844617/65aa1ea4-f50b-4bf4-ac83-afbea0cc7564)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version v2.9

**Additional context**
The duplicate note can be found at the 26.3 timestamp under Virgin difficulty in the notes file. Should be a simple fix, at least- it just needs an update to the notes file to remove the duplicate note.

**Comment by komdog** [comment]
Updated! will be pushed next patch
