### ISSUE TITLE
Weird Artifacting on Notes

### ISSUE THREAD

**Issue by icarus-fallen** [bunfan/beat-banger-public#150]
### Discord Tag

icarus_1185

### Issue Description

Sometimes, not every time, the notes will be all glitchy. it's like the top of the note, the middle of it, and the bottom are on different frames and they flicker as well. It is very distracting.

### OS

Windows

### Version

3.3

**Comment by Stefan-Mitric** [comment]
Can you provide a video?

**Comment by 1MPexe** [comment]
No further information was provided.
