### ISSUE TITLE
Bug:  Not recording top combo!!!

### ISSUE THREAD

**Issue by Mammon-Prince-Of-Hell** [bunfan/beat-banger-public#151]
### Discord Tag

@.undeadforlife

### Issue Description

I may just not understand the reason yet, but when I perfect the Expert level on Cathy [I'm not good enough for the others yet] I don't get the six stars. I also did not get a personal best on that attempt, so there is a possibility that ir didn't record my top combo with 100 accuracy because I didnt get a PB. Pls fix, I worked so hard to get that six stars! ;'[

### OS

Windows

### Version

3.3

**Comment by Stefan-Mitric** [comment]
Can you provide a video?

**Comment by Mammon-Prince-Of-Hell** [comment]
I dont currently have a screen recording software installed, tho I can get
one, and I will try my best to recreate it.

**Comment by 1MPexe** [comment]
Can't seem to reproduce this bug, seems to be working on the latest version.
