### ISSUE TITLE
Bug: Mods Animations disappear or freeze while playing a chart.

### ISSUE THREAD

**Issue by Knipppi** [bunfan/beat-banger-public#153]
### Discord Tag

@knipppi

### Issue Description

After this update, I keep getting this bug where the animation would either disappear for a frame or two OR freeze, but it is noticeable. It isn't unplayable but inconvenient. I have tried verifying the integrity of the files, uninstall and reinstall, reset my whole pc (not because of the game, but personal reasons), also updated the graphics drivers. If there is a fix for it or something pls tell me. Also, how do I open game logs.

### OS

Windows

### Version

3.3

**Comment by Stefan-Mitric** [comment]
Can you provide a video?

**Comment by Knipppi** [comment]
It is very random but I'll attach it as soon as it happens.

**Comment by Knipppi** [comment]
@Stefan-Mitric I think I've found the issue. its the h-mode thingy where the screen should transition to white. maps that use it have been messed and notes are not what they are supposed to be. I found this while trying one of the maps that ive made and it keeps bugging. also where the "skip" note (line note) should be it is replaced with a "press" (normal note).

**Comment by Stefan-Mitric** [comment]
On which version are you playing, and is it a converted mod?

**Comment by Knipppi** [comment]
@Stefan-Mitric latest version, not converted mods (they work perfectly), and the mods that got messed are from last patch/version.

**Comment by Knipppi** [comment]
also it isn't the horny-mode/tool its the modified stuff just checked some mods and files. the hollow note and the line notes are the ones that are causing the issues mostly. also is the beat charter getting an update to suit the new engine or are the next updates going to take over the charter (utility/creation)?

**Comment by Stefan-Mitric** [comment]
The newest version is 3.3, which do you have and which are you using: Steam or  Itch.io?
I ask you this because we no longer have the horny mode/tool in the newest version of the game.

**Comment by Knipppi** [comment]
Steam version.

**Comment by Stefan-Mitric** [comment]
On the bottom right which number do you see?

**Comment by Knipppi** [comment]
v3.3, the latest update

**Comment by 1MPexe** [comment]
Since this is an issue regarding a specific mod. Contact the creator of said mod as we do not have the ability to edit others mods for the game.
