### ISSUE TITLE
Muffled song audio on Restart

### ISSUE THREAD

**Issue by cursedfoxy** [bunfan/beat-banger-public#155]
### Discord Tag

@cursedfoxy

### Issue Description

If you intentionally miss a note and then restart the song, it'll restart muffled instead of playing at the desired volume set in options. Noticed this mostly in mod songs. I'm sure it affects the original levels as well.

### OS

Windows

### Version

3.3

### Relevant log output

```shell
No logs
```

**Comment by Stefan-Mitric** [comment]
Fixed in Small Hotfix Version 3.31
