### ISSUE TITLE
Horny notes are disabled

### ISSUE THREAD

**Issue by suicitem** [bunfan/beat-banger-public#156]
### Discord Tag

@suicitem

### Issue Description

The notes with white and purple frames are disabled or not displayed in the game, which causes certain mods that used them to enter a softlock, rendering them unplayable or causing the rhythm to be disrupted. Here is a mod that uses both of the aforementioned elements: https://discord.com/channels/789252395015733248/1131708891101679776/1131708891101679776

### OS

Windows

### Version

3.3

**Comment by Stefan-Mitric** [comment]
It works on my end. Which Version of the game do you have? 
Do you use the Steam or Itch.io?

**Comment by suicitem** [comment]
> It works on my end. Which Version of the game do you have? Do you use the Steam or Itch.io?
Steam version

**Comment by Stefan-Mitric** [comment]
The version number on the bottom right should be 3.3 if not update.

**Comment by suicitem** [comment]
the game is updated, i reinstalled the mods and the game but the bug still there. The mod is playable, but it replaces the special notes with the default ones, which causes a softblock in other mods when the song ends with these special notes

**Comment by 1MPexe** [comment]
Is this issue still occurring?

**Comment by suicitem** [comment]
yep, the issue still there and i reinstalled all my pc

**Comment by komdog** [comment]
Should be fixed in 3.34 - Dev 1
