### ISSUE TITLE
Bug: Game Crashes

### ISSUE THREAD

**Issue by Dhemuth** [bunfan/beat-banger-public#157]
### Discord Tag

dhemuth

### Issue Description

It crashes after I finish a song, specifically Zoe. and while I still unlock the next level, get a score for the level and the money reward, it's impossible to unlock her cutscene.

Edit: Side note, I can't find where to show the buttons being shown to me from ps4 buttons to keyboard buttons.

### OS

Windows

### Version

3.3

**Comment by Stefan-Mitric** [comment]
Duplicate of #84
