### ISSUE TITLE
options: Button change Z to space bar

### ISSUE THREAD

**Issue by animated4life** [bunfan/beat-banger-public#158]
### Discord Tag

@Nub1818

### Issue Description

When I changed the z button to space bar, it would appear to be changed but it wouldn't really work. found out it would only change the appearance but not the function of the button itself.  Basically I changed it to space bar, it shows I changed it but it would not work unless I use the old z button.

### OS

Windows

### Version

3.3

**Comment by animated4life** [comment]
sorry I meant it for 2.9 but I can show the vid if need be still

**Comment by Stefan-Mitric** [comment]
for the version 2.9?

**Comment by animated4life** [comment]
yeah before it updated, mb mb

**Comment by Stefan-Mitric** [comment]
If you are referring to version 2.9, please note that this GitHub Issues page is intended for current versions only. We are not seeking to enhance or fix older releases.
