### ISSUE TITLE
Beat Bar still appearing in Hands Free Mode

### ISSUE THREAD

**Issue by SeerXela** [bunfan/beat-banger-public#160]
### Discord Tag

seerxela

### Issue Description

In hands free mode, the beat bar is still visible, this was not the case in the previous version of the game, is this going to be an option in the "secret shop" when it is found? is this just how you have chosen to do "hands free mode" going forward?

I personally find it very distracting and have been hoping this was a bug that will be fixed, but if it is intentional then could a setting be added to remove it during hands free as i much prefer the mode without it.

### OS

Windows

### Version

3.3

**Comment by Stefan-Mitric** [comment]
When you turn off the HUD, the beat bar is not included in the HUD.
