### ISSUE TITLE
Cutscenes not unlocking

### ISSUE THREAD

**Issue by Chunk1101** [bunfan/beat-banger-public#161]
### Discord Tag

Slick

### Issue Description

I recently installed the latest version of Beat Banger and I went to complete the stages as usual, but the game crashed after I beat Zoe's level. I opened it back and tried to play but nothing would unlock and I couldn't earn money. Rebooting the game seems to have fixed it though. Loving the new ui design btw.

### OS

Windows

### Version

3.3

**Comment by Stefan-Mitric** [comment]
Duplicate of #84
