### ISSUE TITLE
Bug: No Hud mod isn't functional

### ISSUE THREAD

**Issue by ohm4771** [bunfan/beat-banger-public#163]
### Discord Tag

.vera208

### Issue Description

No Hud mod doesn't work

https://github.com/bunfan/beat-banger-public/assets/149465328/c12d44ce-3ee3-461a-b88f-6eed9c6c1b02

### OS

Windows

### Version

3.3

**Comment by Stefan-Mitric** [comment]
When you turn off the HUD the beat bar is not included in the HUD.
