### ISSUE TITLE
Feature: Default Handsfree on modded levels

### ISSUE THREAD

**Issue by Yasone12** [bunfan/beat-banger-public#166]
### Discord Tag

ImYasone

### Describe the feature you would like

Make it so that a modded level can be autoplayed by default, I'm the one that payed for the game and I can't even use the non official content I add on however I want, In my mind, if it's not tied to the progression of the real game and its in game store, why are you taking options away? so just make it so modded levels can be played hands free.

**Comment by komdog** [comment]
We want to give the mod creators the option to allow level progression in their mod packs. The mod creators will be able to enable hands-free levels to be unlocked by default in a setting we'll be putting in the `mod.cfg` configuration file. But, making every level hands-free by default may ruin the experience that some mod packs are trying to create.
