### ISSUE TITLE
Escape Key Not Working

### ISSUE THREAD

**Issue by redgamemaster** [bunfan/beat-banger-public#169]
### Discord Tag

@redgamemaster_1991

### Issue Description

After the most recent update my escape key no longer works keeping me from accessing all of the relevant menus.

### OS

Windows

### Version

3.3

### Relevant log output

```shell
No log output.
```

**Comment by redgamemaster** [comment]
That fixed it, thank you.

________________________________

**Comment by Stefan-Mitric** [comment]
Fixed in small Hotfix Version 3.31
