### ISSUE TITLE
The faces on the difficulties for Gale are wrong I think

### ISSUE THREAD

**Issue by Free0Bird** [bunfan/beat-banger-public#17]
**Describe the bug**
When you're choosing which difficulty to play on Gales level, the faces on the difficulties do not scale in eroticism(?) like the other characters do.

**To Reproduce**
1. Go to the difficulty menu for Gale
2. Look at the faces and see they are all the same
3. See error

**Expected behavior**
For it to be different faces I guess?

**Screenshots**
![download jpeg](https://github.com/bunfan/beat-banger-public/assets/24922242/98b666da-0a14-46c5-b29f-bcb0881b5707)

**Desktop (please complete the following information):**
 - OS: SteamOS Holo [Steam Deck]
 - Version 3.4.8

**Additional context**
Sorry if this is intentional, lol

**Comment by komdog** [comment]
Good catch! I'll be sure to fix that next patch
