### ISSUE TITLE
Bug: The hands-free option will not work.

### ISSUE THREAD

**Issue by NickaSDAFEAFASDADAS** [bunfan/beat-banger-public#170]
### Discord Tag

_bammy_bam_

### Issue Description

I've ensured that I have 5 stars on every single modpack that I own for the released version of beat banger. The last patch seemed like nothing but bug fixes- but when I had gone to my mod packs for some shenanigans in which you and I both know of,  the option to play the level hands-free was missing. I've been using this feature ever since I first got beat banger, and strangely even when I've lost all my data, it still allowed me to play the mods hands-free. I 5 starred the mods once more when this problem came up, yet it still persisted in not allowing me to have the hands-free option. I hope this gives you enough information! Have a fantastic day!! :D

### OS

Windows

### Version

3.3

**Comment by komdog** [comment]
I can't reproduce the bug. Do you have any screenshots, recordings, or logs? You can check your logs by pressing `F2` and typing `open logs` in the console.

**Comment by 1MPexe** [comment]
Bug not capable of being reproduced.
