### ISSUE TITLE
Internal Controller Ports Bug when multiple controllers are connected

### ISSUE THREAD

**Issue by dude98** [bunfan/beat-banger-public#171]
### Discord Tag

@dude98

### Issue Description

When Using Multiple gamepads, the internal controller ports have some weird issues.
P1 can navigate the menus with the Dpad, other ports cannot, but everyone can hit notes. (probably not a bug)
Connecting a Dualsense controller as P1 then connecting an Xbox controller as P2 shows Xbox Prompts. (P2's Button Prompts)

Connecting an Xbox Controller as P1 then connecting a Dualsense Controller as P2 will show Playstation prompts (P2's Button Prompts) until you disconnect P1, after doing so, the game will return to Keyboard prompts. at this point, reconnecting P1 will put Xbox Prompts (P1's Button Prompts) on screen, while disconnecting and reconnecting P2 will keep them on Keyboard. The Dualsense controller is locked to P2, unable to switch to P1 even if no other controller is connected when it's reconnected.
at this point even connecting a third controller (to replace P2 before it's connected) doesn't work, the icons still won't show up when the Dualsense is reconnected.

If possible, it'd be a good idea to either make a force toggle for controller prompts (options menu selector with "Automatic, Keyboard, Xbox, Playstation, Or Switch" as options or make any controller that gets disconnected go into the first available controller port and making sure controllers can't reserve ports. while possibly making the game always show port 1's controller prompts instead of the latest connected controller.

### OS

Windows

### Version

3.3

**Comment by Stefan-Mitric** [comment]
The detailed gamepad issues described might seem critical, but in reality, they're likely negligible since few players connect multiple controllers or encounter such scenarios. It's an edge case, not a widespread concern.
