### ISSUE TITLE
Clearer descriptions for item unlock requirements.

### ISSUE THREAD

**Issue by DaringFlash** [bunfan/beat-banger-public#175]
### Discord Tag

Daring_Flash#1948

### Describe the feature you would like

for modifiers like and especialy No Fail a clearer description on the effects it does as in does it have reduced score? does it count as handfree mode? what does it do outside of not making you able to fail the song?. and for the unlock recuirement like most songs are in the store i get that but it unlock screen / extras it doesnt tell the source to which its obtained for secrets like the shopkeeper one i get it keep it hidden or mysterious but for the others it doesnt tell like un an bar underneath the picture while selected its could say for for example for double stuffed : Picture can be bought in shop. or for an unlockable one [example name here]: Can be obtained foby getting 6 stars on [Character name here] on [difficulty name here].

**Comment by komdog** [comment]
#174 #178

**Comment by komdog** [comment]
#185
