### ISSUE TITLE
Game launches and works but no screen visuals.

### ISSUE THREAD

**Issue by AeGitz** [bunfan/beat-banger-public#176]
### Discord Tag

@note_52

### Issue Description

Hi, I just purchased this game but when I launch it the game shows the beat banger image before going back to desktop. When I alt tab its just a grey screen. Does seem to have sound and registers my key inputs but no visuals. 

### OS

Windows

### Version

3.3

**Comment by AeGitz** [comment]
Never mind issue was solved due to multiple monitors and full screen. Somehow disconnecting the monitors and having the application start on windowed mode solved it.

**Comment by Stefan-Mitric** [comment]
Solved
