### ISSUE TITLE
Bug: Settings issues

### ISSUE THREAD

**Issue by SaddoBoi** [bunfan/beat-banger-public#180]
### Discord Tag

@SadBoiOnline

### Issue Description

changing audio settings affects nothing (i.e. turning down voices, sfx, or music will still have music on during the map) & no HUD modifier still keeps the HUD enabled 

### OS

Windows

### Version

3.3

**Comment by Stefan-Mitric** [comment]
Can you explain what you mean by map? 
Do you mean the cutscenes or when you play the level itself?

**Comment by komdog** [comment]
I fixed it in the backend I'll push it out in v3.4
