### ISSUE TITLE
Max combo isn't update

### ISSUE THREAD

**Issue by DriveTGPR** [bunfan/beat-banger-public#182]
### Discord Tag

drivetg

### Issue Description

Due to the migration from Unity to Godot the current score had been lost, I decided to go back to having the max combo on all difficulties, but I have noticed that when you get the 5 stars and not the maximum combo, once you try again and get the max combo, number in menu isn't updated.

I use the Steam version. I leave the two examples where it happened to me, in both I got the maximum combo on my second attempt.

[Example 1](https://i.gyazo.com/a440c817c00b809fd9e67dcc64ed23fd.png)
[Example 2](https://i.gyazo.com/6f262acd8adb78f4ceb419c9cf7c5f5f.png)

### OS

Windows

### Version

3.3

**Comment by 1MPexe** [comment]
Bug has been resolved. #202
