### ISSUE TITLE
Mod not moving/frozen

### ISSUE THREAD

**Issue by RenaiChillax** [bunfan/beat-banger-public#183]
### Discord Tag

miles_morales.gwen_stacy

### Issue Description

so basically in a mod, it was perfectly fine, but all of a sudden when i restart the game and play that mod, nothing moves only those keys to play the beat, i can still die/get in menu or miss the beat, but those beats are frozen.

### OS

Windows

### Version

3.3x (Steam)

**Comment by RenaiChillax** [comment]
the game is fine, only that one specific mod.But it worked before so idk..

**Comment by RenaiChillax** [comment]
currently the mods wont update, it only can be removed but not added.

**Comment by RenaiChillax** [comment]
> What mod were you trying to play? It could be that the mod is not compatible with the new version or it could be your CPU/GPU making the game freeze or something

i was trying to play the Kuromi, the thing is that that mod folder wont update. 
CPU:R5 3600 
GPU:RX6800

**Comment by RenaiChillax** [comment]
> > > What mod were you trying to play? It could be that the mod is not compatible with the new version or it could be your CPU/GPU making the game freeze or something
> > 
> > 
> > i was trying to play the Kuromi, the thing is that that mod folder wont update. CPU:R5 3600 GPU:RX6800
> 
> The release version or the legacy version? Because there are 2 release mod and 1 legacy mod. Can't check ATM since I'm not at my house rn and I'm assuming that you are playing on release 3.31

i played the easy and hard, the hard one was playable then suddenly cant be played, I've changed mod folder and in game nothing changed.I've removed all the game but i cant insert any.

**Comment by DoodleSurf** [comment]
> currently the mods wont update, it only can be removed but not added.

Check the mod folder in question, open keyframes.cfg inside of it with a notepad and check for `bpm.mc` field if there is one, rename it from `bpm.mc` to `bpm`

**Comment by 1MPexe** [comment]
Can't seem to reproduce this bug.
