### ISSUE TITLE
possable issue with unlocking photos after beating expert mode

### ISSUE THREAD

**Issue by Euline77** [bunfan/beat-banger-public#185]
### Discord Tag

Orion

### Issue Description

hay, um, so i got 5 starts on ''she doesent like you'' expert mode but nothing unlocked 

when i compleated expert mode on the first one with cathy a new photo unlocked, and i noticed i have 3 photos yet to be unlocked but nothing for the latest unlock

im sure im ment to get an unlock

### OS

Steam Deck (Linux)

### Version

3.3x (Steam)

**Comment by 1MPexe** [comment]
The unlock conditions for beating Zoe are different. Those conditions will be explicitly stated in the next update.

**Comment by komdog** [comment]
👍 This issue was previously addressed in another ticket. As 1mp mentioned earlier, it will be fixed in the next release.
