### ISSUE TITLE
Bug:  Trouble connecting Lovense

### ISSUE THREAD

**Issue by FlannyFlan** [bunfan/beat-banger-public#189]
### Discord Tag

Flandren

### Issue Description

I tried to enter the port to connect my lovense but it won't let me type anything. I simply cannot type my port in. I tried pressing the numbers or any key to be honest and nothing happens. The only key that functions is the back key which brings me back to stage selection.

### OS

Windows

### Version

3.3x (Steam)

**Comment by DoodleSurf** [comment]
Can you provide a screenshot or a video?

**Comment by 1MPexe** [comment]
Is this issue still occurring?

**Comment by 1MPexe** [comment]
No further information was provided.

**Comment by DrBaron420** [comment]
I just tried to connect my Solace to the game and I was having the same issue.

The box that let's me input the IP and Port would not get selected and could not get anything typed in to the boxes.
