### ISSUE TITLE
Launching the game from different links (shortcuts, the .exe in the file, and from steam) lead to different saves

### ISSUE THREAD

**Issue by Sangheili9235** [bunfan/beat-banger-public#190]
### Discord Tag

@Sangheili

### Issue Description

Exactly as the title says

### OS

Windows

### Version

3.3x (Patreon)

**Comment by Sangheili9235** [comment]
Sorry I need to add what that means.
All progress is lost on levels, mods included, and this is not correlated to version update related wipes, I tested it before I thought I had gone crazy.

**Comment by DoodleSurf** [comment]
Couldn't reproduce the bug.
Ran the game from Steam shortcut, from the .exe, from a separate shortcut from that .exe, from separate steam:// shortcut - the save data still persisted.

Can you record the bug in action?

**Comment by Sangheili9235** [comment]
well shit

I tried to reproduce it and it seems to not be happening anymore.

Either it was a one time thing or I'm dumb

Thanks for looking though

**Comment by komdog** [comment]
Seems resolved so closing
