### ISSUE TITLE
Heart Loss Sound in No-Fail Mode?

### ISSUE THREAD

**Issue by 1MPexe** [bunfan/beat-banger-public#199]
### Issue Description

The heart loss noise still plays in no fail mode but it only plays the noise based on the amounts of hearts the character has left. When all hearts WOULD be gone, the noise stops playing. However it returns when you hit a few notes and get a few hearts back.

### OS

Windows

### Version

3.3x (Patreon)

**Comment by komdog** [comment]
Fixed
