### ISSUE TITLE
No more joystick support?

### ISSUE THREAD

**Issue by Free0Bird** [bunfan/beat-banger-public#20]
**Describe the bug**
I may be misremembering, but didn't last patch let you use your controller joystick? I remember because it would spaz out, but now it seems to be completely removed?

**To Reproduce**
1. Go to the game
2. Try and use a controller thumbstick
3. Notice that it doesn't do anything

**Expected behavior**
I expected it to highlight and scroll through menu elements

**Desktop (please complete the following information):**
 - OS: SteamOS Holo [Steam Deck]
 - Version 3.4.8

**Additional context**
Sorry if I am mistaken, or if this is intentional

**Comment by komdog** [comment]
We've removed joystick support for now due to a bug where the joystick would deliver constant inputs to the input handler. We'll find a solution for this shortly and bring back the ability to use the joystick in the menus.
