### ISSUE TITLE
Should add a way to disable the penalty for missing 

### ISSUE THREAD

**Issue by ColeShark** [bunfan/beat-banger-public#20]
if someone just wants to play without focusing entirely on the game its very easy to loose

**Comment by AnonymousXEN** [comment]
Maybe the debug menu would be the best place to implement this? Essentially a 'cheat' code!

**Comment by komdog** [comment]
**This is already a feature included in the game accessed through the debug console on the main menu.** on version 0.02 of the game, the "auto-play" can be accessed by typing `lazybones` in the debug console and pressing `enter`. This command may change in later versions of the game.
