### ISSUE TITLE
Max Combo Not Updating

### ISSUE THREAD

**Issue by IntroLifee** [bunfan/beat-banger-public#202]
### Discord Tag

@introlife

### Issue Description

I beat Cathy expert level with 100% accuracy, but the game didn't save my progress after I pressed Y to skip the cutscene

https://github.com/bunfan/beat-banger-public/assets/111629644/383818c3-b106-4cc8-aa8e-8c1ae217c730

### OS

Windows

### Version

3.34 dev1 (Steam)

### Relevant log output

```shell
I don't have any ideas where are these logs located
```

**Comment by 1MPexe** [comment]
I can't seem to reproduce this bug.

**Comment by 1MPexe** [comment]
#182

**Comment by Stefan-Mitric** [comment]
Here is the fix. 

````gdscript
static func write_level_save(saved_data):
	saved_data['grade'] = Game.grade
	saved_data['score'] = Game.score
	saved_data['max_combo'] = Game.max_combo
````
