### ISSUE TITLE
Issues with Beat Banger 

### ISSUE THREAD

**Issue by Mike13q1313** [bunfan/beat-banger-public#207]
### Discord Tag

emanuel987

### Issue Description

A link to go to their discord on beat banger is not working and says invalid whenever press many other people are having the same problem. 

### OS

Windows

### Version

3.34 dev1 (Steam)

**Comment by Mike13q1313** [comment]
These is also on Steam that I have noticed that the link is not working.

**Comment by komdog** [comment]
Does this work? [discord.gg/beatbanger](discord.gg/beatbanger)

**Comment by Mike13q1313** [comment]
Yes, it works. thx
