### ISSUE TITLE
Game window at Edge of Monitor and Cannot be Moved

### ISSUE THREAD

**Issue by markusNirpaw** [bunfan/beat-banger-public#208]
### Issue Description

When the game is launced, the main menu window appears off the top half of my monitor (ultrawide). Cant access any sort of control to move it or recenter it to my screen; alt-enter wont make game full screen. 

### OS

Windows

### Version

3.34 dev1 (Steam)

**Comment by 1MPexe** [comment]
Could you provide video of the bug?

**Comment by 1MPexe** [comment]
Is this issue still occurring?

**Comment by 1MPexe** [comment]
No further information provided.
