### ISSUE TITLE
Keybind ESC Soft-lock

### ISSUE THREAD

**Issue by TheGamingRizzler** [bunfan/beat-banger-public#209]
While playing beat banger I have done possibly the dumbest things ever, while changing key binds I accidentally press ESC on my confirm key and it is now impossible to fix. I do not know if it is possible to fix this issue and I just wanted to know if there was anything I could do to fix my idiotic mistake, if not I understand thank you and goodnight

**Comment by 1MPexe** [comment]
Press f2 and type open keybinds

delete everything in the text file

save and restart.
