### ISSUE TITLE
I would want the newest glitch to be a future gameplay element

### ISSUE THREAD

**Issue by Free0Bird** [bunfan/beat-banger-public#21]
**Describe the feature you'd like**
Now this may seem weird, but the newest glitch in the Gale level with the double button press layered ontop of eachother? That was honestly cool. Of course it would need tweaking to be more user friendly, but layered beats (either the same beat or 2 different ones like A and X) would be a super fun and engaging addition to the game in my opinion. Whether they be pre-placed in levels, or an optional "extra" you can turn on or off to make the game more fun, I think personally it could be enjoyable.

**Additional context**
Like a dance dance revolution split for your fingers, lol

**Comment by komdog** [comment]
Moved to #61
