### ISSUE TITLE
Custom (mod) songs notes dont move and songs doesnt play (BUG, VIDEO PROOF)

### ISSUE THREAD

**Issue by SkylerDaKat** [bunfan/beat-banger-public#210]
### Issue Description

I saw this was reported before but the bug couldn't be reproduced - 
Well this happened to me before, on two of my devices already, 

So this is how I reproduced the bug, 
I launch the game and launch the mod, yeah
but I also found the "fix" (?)
Basically, load one of the base game levels and then load the mod

Honestly one of the biggest, weirdest mods issues I've experienced.
definitely not a hardware issue as it happened on two different laptops with very different hardware
[2023-12-27 06-22-40.zip](https://github.com/bunfan/beat-banger-public/files/13779223/2023-12-27.06-22-40.zip) (the video proof, I can't send mkv videos so sending as zip)

I'm not a dev, but I think something fails to load on some installations of Beat Banger and don't fully load on 3rd party code,
although annoying, it just takes loading the base level and then playing the mods.

I hope this bug can finally be reproduced now, which by the way, I got your game as a christmas present and I love it, and for some reason, it reminds me of Taiko No Tsujin or the dangaronpa one that appears in the first game for like, one time

anyways, hopefully this can be fixed

### OS

Windows

### Version

3.34 dev1 (Steam)

**Comment by Stefan-Mitric** [comment]
Is already fix in the Build v3.34 - dev2
