### ISSUE TITLE
Lovense Connecting

### ISSUE THREAD

**Issue by PopcornIceCream** [bunfan/beat-banger-public#212]
### Issue Description

![Screenshot 2023-12-31 221451](https://github.com/bunfan/beat-banger-public/assets/155327251/6e913f74-b2a4-4f2d-b0e8-dc8f42981b77)

The Game finds the toy but does not send vibrations to it. Has worked before and works on other games.

### OS

Windows

### Version

3.31 (Steam)

**Comment by PopcornIceCream** [comment]
Yea I'm using the remote app on pc and connecting trough local host has worked before and works on other games with lovesense support.

**Comment by 1MPexe** [comment]
Which toy are you using and have you tried using the mobile application?

**Comment by PopcornIceCream** [comment]
Tried with mobile application it does work, so might be issue then with the dekstop app with never versions

> The steam version has been updated to "3.34dev". Have you tried using the mobile application?
