### ISSUE TITLE
Discord Moderation + Discord Link On Itch.io download dead link

### ISSUE THREAD

**Issue by Knightly12** [bunfan/beat-banger-public#214]
### Discord Tag

Knightly#6833

### Issue Description

Didn't know any other avenue.

Discord Mod is unhinged. Banned from server for posting "cursed" emoji despite not breaking any of the rules in both the general chat nor the rules section. No reason given as to ban, above line is only reason I can think of.

Also, discord link that is provided through the game is a dead link, doesnt open up to discord server. And yea this was tried before the ban. 

Paid and downloaded from Itch.io page. Version 3.3.4.1

### OS

Windows

### Version

3.33 (Patreon)

**Comment by 1MPexe** [comment]
The links seem function correctly. As for your ban, you may have broken one of our server rules.
