### ISSUE TITLE
instant fail

### ISSUE THREAD

**Issue by JunkratYT** [bunfan/beat-banger-public#215]
### Discord Tag

_mist8772_

### Issue Description

whenever i try to play a map either modded or story the game instantly fails me and if i have no fail on then i just get the win screen and nothing else

### OS

Windows

### Version

3.33 (Patreon)

### Relevant log output

```shell
USER ERROR: Condition "hr != ((HRESULT)0x00000000)" is true. Returning: ERR_CANT_OPEN
   at: audio_device_init (drivers/wasapi/audio_driver_wasapi.cpp:275)
USER ERROR: WASAPI: init_output_device error
   at: init (drivers/wasapi/audio_driver_wasapi.cpp:562)
```

**Comment by JunkratYT** [comment]
and this is on team version

Godot Engine v4.2.stable.official.46dc27791 - https://godotengine.org
OpenGL API 3.3.0 NVIDIA 546.17 - Compatibility - Using Device: NVIDIA - NVIDIA GeForce GTX 1050 Ti
USER ERROR: Condition "hr != ((HRESULT)0x00000000)" is true. Returning: ERR_CANT_OPEN
   at: audio_device_init (drivers/wasapi/audio_driver_wasapi.cpp:275)
USER ERROR: WASAPI: init_output_device error
   at: init (drivers/wasapi/audio_driver_wasapi.cpp:562)
 
23:49:47: INFO Loading Save Data...
23:49:47: INFO Validating Save...
23:49:47: INFO Saving Game...
23:49:47: INFO Loading User Settings...
USER ERROR: Unable to convert array index 0 from 'Nil' to 'String'.
   at: assign (core/variant/array.cpp:245)
23:49:47: INFO Validating Keybinds...
23:49:47: INFO Loading Keybinds...
WARNING: AnimationMixer: 'RESET', Value Track: '.:default_color' has different update modes between some animations which may be blended together. Blending prioritizes UpdateMode.UPDATE_CONTINUOUS, so the process treats UpdateMode.UPDATE_DISCRETE as UpdateMode.UPDATE_CONTINUOUS with InterpolationType.INTERPOLATION_NEAREST.
   at: _update_caches (scene/animation/animation_mixer.cpp:889)

**Comment by JunkratYT** [comment]
for some reason having my headphones unplugged was the issue lol its all good now

**Comment by Stefan-Mitric** [comment]
Solved
