### ISSUE TITLE
Lovense sync

### ISSUE THREAD

**Issue by IthilwenGalanodel** [bunfan/beat-banger-public#216]
### Discord Tag

ithilwen_galanodel

### Issue Description

The instructions are not clear or accurate enough for lovense sync. When I try to add the ip and port it is just a grayed out button and wont let my attempt to connect at all

### OS

Windows

### Version

3.34 dev1 (Steam)

**Comment by 1MPexe** [comment]
Is this issue still occurring? Can you provide more information?

**Comment by IthilwenGalanodel** [comment]
Yes I am still having the issue, when I try to attach a screenshot I keep
getting a too large message but when I go to the lovense option in the menu
nothing happens when I select connect and there's no option for ip

**Comment by IthilwenGalanodel** [comment]
I am sorry, I may have misinterpreted the instructions. I got it working in
the end

**Comment by 1MPexe** [comment]
Happy to help.

**Comment by 1MPexe** [comment]
Issue resolved.
