### ISSUE TITLE
Invisible note

### ISSUE THREAD

**Issue by Juipter247** [bunfan/beat-banger-public#217]
### Discord Tag

@jupiter_247

### Issue Description

There was a bug where I was able to hit a note from my previous attempt before the song started.

https://github.com/bunfan/beat-banger-public/assets/156986933/99cc6ce3-639c-437a-8f10-02f3a8c85f67

### OS

Windows

### Version

3.34 dev1 (Steam)

**Comment by 1MPexe** [comment]
Is this bug still occurring?

**Comment by Juipter247** [comment]
> Is this bug still occurring?

I have not been able to replicate this exact bug, no.

**Comment by 1MPexe** [comment]
I can't seem to replicate this but.

Though this may have been likely connected to godots engine and their current issue with Xbox controllers causing double inputs.

If all seems well then it should run as intended.
We'll keep a lookout for this bug in the future.
