### ISSUE TITLE
gale level randomly stopping

### ISSUE THREAD

**Issue by RedKnifeRK** [bunfan/beat-banger-public#22]
Every single time I play gale's level, no matter the difficulty level chosen, a few moments after the part where she's don't giving you a titfuck and starts riding you, the level randomly stops and you can't do anything except fail or exit level.

**To Reproduce**
1. Open beat banger.
2. Go to "Play"
3. Select Gale's level, the difficulty doesn't matter
4. Play like normal 
5. Eventually while shes riding you the level will just stop.

**Expected behavior**
I expected to just play the level like normal

**Screenshots**
Screenshots wouldn't really help since it's animated, plus im reporting the bug on mobile.

**Desktop (please complete the following information):**
 - OS: Windows 10 pro
 - Version v2.9

**Comment by komdog** [comment]
Could you give me more context? 
When does the level stop? 
Does it happen every single time? 
Does the animation stop only? or the music too?

**Comment by komdog** [comment]
This most likely will not happen in the latest public build.
