### ISSUE TITLE
Problemas, fiz besteira talvez

### ISSUE THREAD

**Issue by reythehate** [bunfan/beat-banger-public#220]
### Discord Tag

guilhermems2003

### Issue Description

Eu tentei baixar mods no Beat Bnager mas desisti, fui na pasta e apaguei os arquivos mas acho que apaguei algo importante, pois quando aperto em jogar ele da erro

### OS

Windows

### Version

3.34 dev1 (Steam)

**Comment by reythehate** [comment]
Deixa, consegui abrir, tive que mecher muito

**Comment by 1MPexe** [comment]
Issue was resolved by original poster.
