### ISSUE TITLE
mod issue

### ISSUE THREAD

**Issue by Bossu1121** [bunfan/beat-banger-public#221]
### Discord Tag

bossugames

### Issue Description

hey, im having an issue installing mods. yes i followed every tutorial on the discord, but for some reason despite dropping mods into the folder in every way possible, they still wont launch. i do it through winrar, and manually and it still doesnt work, any advice? sorry to bother.

### OS

Windows

### Version

3.34 dev1 (Steam)

**Comment by Stefan-Mitric** [comment]
If you're having trouble installing mods, please consider seeking assistance in the support or modding channels first before submitting a bug report. It's essential to make sure it's a bug before reporting it. You've already tried various methods, but here are a few more steps to try:

1. Ensure you're using the correct mod version compatible with your game.
2. Follow installation instructions precisely, placing mod files in the right folder.

The community in those channels may offer valuable insights to help you resolve your issue. Don't hesitate to ask for help there!

Issue resolved as it is not a genuine bug.
