### ISSUE TITLE
6-star on Zoe

### ISSUE THREAD

**Issue by clark792** [bunfan/beat-banger-public#223]
### Issue Description

I don't know if its a bug or not but I got a perfect combo on Zoe and it has no 6 star or blue mark. Do you have to get a certain score to 6 star the level or just max combo.

### OS

Windows

### Version

3.31 (Steam)

**Comment by 1MPexe** [comment]
You are running on version 3.31 on steam?

**Comment by clark792** [comment]
> You are running on version 3.31 on steam?

im running 3.34

**Comment by 1MPexe** [comment]
Could you provide video of the bug?

**Comment by clark792** [comment]
> Could you provide video of the bug?

i probably cant do it again

**Comment by Stefan-Mitric** [comment]
Could relate to the bug that we had in the past #182 and #202.

**Comment by 1MPexe** [comment]
This issue has been resolved and will be fixed in the next update.
