### ISSUE TITLE
Version 3.36 Level editor does not work

### ISSUE THREAD

**Issue by Sangheili9235** [bunfan/beat-banger-public#224]
### Discord Tag

@Sangheili

### Issue Description

Upon opening a mod or even the blank template it generates it only shows a blank menu with a generic level editor tag in the top right (which oscillates in a slow jittery manner) and the keybinding reminders for select and exit.  I attempted an install in a separate location to see if it was an overwrite issue and it does not appear to be the case. The cmd log will be in the attached .txt due so character limitations.
[Cmd logs for Beat Banger V_3_36.txt](https://github.com/bunfan/beat-banger-public/files/14075425/Cmd.logs.for.Beat.Banger.V_3_36.txt)

### OS

Windows

### Version

3.34 dev1 (Steam)

**Comment by komdog** [comment]
Looks like there's an issue when copying template files from the resources folder to the user's file system. I'll see what I can do to fix this.

**Comment by komdog** [comment]
Fixed in 3.5
