### ISSUE TITLE
Lovense Mode Not Connecting

### ISSUE THREAD

**Issue by G1rma** [bunfan/beat-banger-public#226]
### Discord Tag

@Girma

### Issue Description

I can't seem to connect my Lovense and Beat Banger together for whatever reason. I've looked into my firewall and adjusted the settings concerning the UPnP and allowed those, I've made sure that I am on the same network, and have re-installed the Lovense app in case that was the issue. I have no idea what it could be and feel like I am just constantly Beat Banging my head against a wall. Any and all help would be appreciated 😿 

### OS

Windows

### Version

3.34 dev1 (Steam)

### Relevant log output

```shell
Godot Engine v4.2.stable.official.46dc27791 - https://godotengine.org
OpenGL API 3.3.0 NVIDIA 536.99 - Compatibility - Using Device: NVIDIA - NVIDIA GeForce RTX 3060 Ti
 
14:59:47: INFO Loading Save Data...
14:59:47: INFO Validating Save...
14:59:47: INFO Saving Game...
14:59:47: INFO Loading User Settings...
USER ERROR: Unable to convert array index 0 from 'Nil' to 'String'.
   at: assign (core/variant/array.cpp:245)
14:59:47: INFO Validating Keybinds...
14:59:47: INFO Loading Keybinds...
WARNING: AnimationMixer: 'RESET', Value Track: '.:default_color' has different update modes between some animations which may be blended together. Blending prioritizes UpdateMode.UPDATE_CONTINUOUS, so the process treats UpdateMode.UPDATE_DISCRETE as UpdateMode.UPDATE_CONTINUOUS with InterpolationType.INTERPOLATION_NEAREST.
   at: _update_caches (scene/animation/animation_mixer.cpp:889)
```

**Comment by 1MPexe** [comment]
Have you allowed beat banger access through your pc's firewall?

**Comment by 1MPexe** [comment]
let's take it from the top.  Make sure your toy is on and available, input your IP and make sure you are assigning the correct port which can be found listed in the apps game mode section...
 After your port and IP are entered, press "connect" and then press the "Test Vibration" button. If the connection is successful the toy should react to pressing the test vibration button.

**Comment by 1MPexe** [comment]
Did this resolve your issue?

**Comment by G1rma** [comment]
Oh sorry! So I found a work around using the hotspot feature for my PC and connecting to the wifi signal it gives off from that.

**Comment by komdog** [comment]
This issue is the network connection issue. Closing as it's been resolved.
