### ISSUE TITLE
Can zoom out on the gallery, but can't zoom in 

### ISSUE THREAD

**Issue by Leomveintemil** [bunfan/beat-banger-public#227]
### Discord Tag

@missingleom

### Issue Description

There is a bug when you try to zoom in on gallery images, but you can zoom out one step perfectly, it's just the zoom **in** function. Using Version 3.43 from itch.io via patreon
Uploading Can zoom out but cant zoom in.mp4…

### OS

Windows

### Version

3.33 (Patreon)

**Comment by Stefan-Mitric** [comment]
Here is the visual proof.

https://github.com/bunfan/beat-banger-public/assets/146543675/2ad4bf29-3336-4638-b07c-d6b0c64c95a0

**Comment by Stefan-Mitric** [comment]
fixed in Version 3.452
