### ISSUE TITLE
game slows down and goes all Staticky

### ISSUE THREAD

**Issue by gocko1114** [bunfan/beat-banger-public#228]
### Discord Tag

gocko

### Issue Description

the game slows down and goes all Staticky. its normally right after i complete a song. and it stays like that even into new song until i restart the game or wait a couple of mins for it to go away after about 5-10 mins.

ram 128gb
cpu ryzen 9 7900x
gpu rtx 4070

### OS

Windows

### Version

3.34 dev1 (Steam)

**Comment by Stefan-Mitric** [comment]
Does this happen often? Can you reproduce it and make a video?

**Comment by Stefan-Mitric** [comment]
Unable to reproduce. Will reopen if issue recurs.

**Comment by youngEphraim** [comment]
https://github.com/bunfan/beat-banger-public/assets/109781887/9ef10810-4d1e-4c78-be84-8634c0a5d7a3

I believe that I'm running into the same issue.
