### ISSUE TITLE
Level Progress Wipe

### ISSUE THREAD

**Issue by hackerTiger21** [bunfan/beat-banger-public#232]
### Discord Tag

@atomicBlaze21

### Issue Description

NOTE: This issue occurs in Version 3.452, which is not an option in the issue form at this time

Prior to updating, I had unlocked all of the released levels. Upon entering the level select menu after the update, I am met with only Cathy's level unlocked with no score records on any difficulty.

What makes this bug especially weird is that my store is just the same as it was with everything unlocked. Even the gallery has everything unlocked, including pictures that have in-game requirements to be unlocked. This makes me think that my save file still exists, but the new version is unable to parse the section that persists level progress and falls back to a default state. Nothing abnormal is shown in logs.

### OS

Windows

### Version

3.34 dev1 (Steam)

**Comment by hackerTiger21** [comment]
Update: I had a single mod installed prior to the update, this mod still works and has retained all of my previous scores. This issue of level progress being wiped appears to only affect the main story levels not mods.

**Comment by hackerTiger21** [comment]
A temporary fix has been discovered. In the `game.sav` file, you can find the key/value pair in the `data` object with a key of `"act_name"` and manually replace the value of that key with `"Beat Banger: Vol.1"`. This rectifies the mismatch caused by the internal rename of Acts to Volumes. However, it would be a good idea to allow the game to recognize the old value name and change it to the new name for the sake of backwards-compatibility with old save files.

**Comment by komdog** [comment]
Should no longer happen in v3.455 this will cause the level to get wiped one last time, but should never happen again as long as the act_id and level_id aren't changed
