### ISSUE TITLE
No music in non-main menus

### ISSUE THREAD

**Issue by hackerTiger21** [bunfan/beat-banger-public#233]
### Discord Tag

@atomicBlaze21

### Issue Description

NOTE: This issue occurs in Version 3.452, which is not an option in the issue form at this time

With the new update, there is no longer any music that plays in any menu that isn't the main menu. The main menu music works just fine, but the act menu and level select menu no longer play any music. I didn't see any mention of a change to menu music in the change log, so I can only assume that this change was unintentional. Nothing in the logs suggest any issue with music loading.

### OS

Windows

### Version

3.34 dev1 (Steam)

**Comment by Stefan-Mitric** [comment]
Fixed in version 3.499
