### ISSUE TITLE
Black Screen of nothing

### ISSUE THREAD

**Issue by MrEspionage** [bunfan/beat-banger-public#234]
### Discord Tag

@pixelbitscript

### Issue Description

I saw the new update and wanted to check it out, so I boot up the game and it goes onto my left monitor instead of my right monitor like it usually does. It then proceeds to do nothing, the name in the taskbar is blank, and when closing it does not call itself "Beat Banger", instead calling itself the engine name "Godot Engine".  There is only a black screen.

### OS

Windows

### Version

3.34 dev1 (Steam)

**Comment by Stefan-Mitric** [comment]
could you provide us with an video proof and the log files. the log files are located in = C:\Users\[your username]\AppData\Roaming\Godot\app_userdata\Beat Banger\logs

**Comment by MrEspionage** [comment]
[beatbanger.log](https://github.com/bunfan/beat-banger-public/files/14303324/beatbanger.log)
[beatbanger2024-02-15T18.08.04.log](https://github.com/bunfan/beat-banger-public/files/14303325/beatbanger2024-02-15T18.08.04.log)
[beatbanger2024-02-14T22.37.52.log](https://github.com/bunfan/beat-banger-public/files/14303326/beatbanger2024-02-14T22.37.52.log)
[beatbanger2024-02-14T21.21.47.log](https://github.com/bunfan/beat-banger-public/files/14303327/beatbanger2024-02-14T21.21.47.log)
[beatbanger2024-02-14T21.18.31.log](https://github.com/bunfan/beat-banger-public/files/14303328/beatbanger2024-02-14T21.18.31.log)

https://github.com/bunfan/beat-banger-public/assets/160087750/84fe2de2-5bb9-463b-bfe3-47238ed5a573

Hopefully this is what you guys need, also sorry for the recording scuff I haven't used OBS in a while.

**Comment by DoodleSurf** [comment]
> [beatbanger.log](https://github.com/bunfan/beat-banger-public/files/14303324/beatbanger.log) [beatbanger2024-02-15T18.08.04.log](https://github.com/bunfan/beat-banger-public/files/14303325/beatbanger2024-02-15T18.08.04.log) [beatbanger2024-02-14T22.37.52.log](https://github.com/bunfan/beat-banger-public/files/14303326/beatbanger2024-02-14T22.37.52.log) [beatbanger2024-02-14T21.21.47.log](https://github.com/bunfan/beat-banger-public/files/14303327/beatbanger2024-02-14T21.21.47.log) [beatbanger2024-02-14T21.18.31.log](https://github.com/bunfan/beat-banger-public/files/14303328/beatbanger2024-02-14T21.18.31.log)
> 2024-02-15.18-19-14.mp4
> 
> Hopefully this is what you guys need, also sorry for the recording scuff I haven't used OBS in a while.

Do you have any overlays installed like from Razer or Nvidia? Also were you happen to set any global graphical settings in your drivers control panel like Nvidia Control Panel or AMD Radeon Settings?

**Comment by MrEspionage** [comment]
I disabled the Nvidia overlay, nothing changed, and I don't think I have ever touched global graphical settings in the Nvidia Control Panel. If you give me a guide for the global graphical settings I can check, but I don't remember ever changing settings in there.

**Comment by Stefan-Mitric** [comment]
Unable to reproduce. Will reopen if issue recurs.

**Comment by MrEspionage** [comment]
I am still unable to open the game

**Comment by DoodleSurf** [comment]
Resetting the primary monitor to be the sole one - forced the game to stay at the first monitor, fixing the issue.
The code for preserving the monitor/game window position is not present in the game, so it seems to be an engine issue.
