### ISSUE TITLE
In game mod creator not saving

### ISSUE THREAD

**Issue by Juipter247** [bunfan/beat-banger-public#236]
### Discord Tag

@jupiter_247

### Issue Description

The following do not save in the level creator: mod creator, song name, and artist. Below are links to the video and message I.D. 

https://discord.com/channels/789252395015733248/1053811398691524638/1207541955110768650

1207541955110768650

https://cdn.discordapp.com/attachments/1053811398691524638/1207541954292752414/2024-02-14_22-18-12.mp4?ex=65e00614&is=65cd9114&hm=c62f8f6db8d0455dccf7d613b8be98ad7c92efa73e96dcd5608072372b68bbac&

### OS

Windows

### Version

3.34 dev1 (Steam)

**Comment by komdog** [comment]
Added Save and Exit Button
