### ISSUE TITLE
Missing/Corrupted inputs with PS controller

### ISSUE THREAD

**Issue by yukiami** [bunfan/beat-banger-public#237]
### Discord Tag

@yukiami

### Issue Description

In Zoe, Gale, and Claire's expert levels button inputs don't appear on the timeline that should be there. In Zoe's level there are corrupted inputs shown as the white dots used in handsfree mode instead of the usual icons.

### OS

Windows

### Version

3.34 dev1 (Steam)

**Comment by yukiami** [comment]
After testing mods this appears in multiple of them, meaning it's probably not an issue with the charting of those charts specifically

**Comment by Stefan-Mitric** [comment]
Closed Due to Misinterpretation, these notes are called ghost notes.
