### ISSUE TITLE
Hands-free mode/ difficulty screen missing from mods (v3.452)

### ISSUE THREAD

**Issue by Sebishosho** [bunfan/beat-banger-public#238]
### Discord Tag

@sebishosho

### Issue Description

This issue happens with single mods with only one difficulty. When I select one, the only option is to play it. There's no difficulty screen, where it shows the difficulty names and stars. I've included Cathy's level as an example of what I mean.
![Screenshot 2024-02-15 014854](https://github.com/bunfan/beat-banger-public/assets/160104971/4f77b648-1e77-4cec-a76b-83da1aec1ff2)

This other one is an example from a single with only one difficulty. After selecting the icon is when the difficulty selection screen would usually come up.
![Screenshot 2024-02-15 014817](https://github.com/bunfan/beat-banger-public/assets/160104971/7e5f085f-3057-44ec-8f9b-c99e05ddb6ab)

All this comes down to is basically no score (stars) and no hands-free mode. For album mods and singles with only one difficulty, everything is fine. Here's an example from each. The Bonbon & Chuchu one is a single and the Polt one is an album.
![Screenshot 2024-02-15 020041](https://github.com/bunfan/beat-banger-public/assets/160104971/1f2d6de8-70db-4072-a5bb-3cd878e340d7)
![Screenshot 2024-02-15 020329](https://github.com/bunfan/beat-banger-public/assets/160104971/f4778acc-162b-4b1b-9709-6112ae98dc59)

### OS

Windows

### Version

3.34 dev1 (Steam)

**Comment by Stefan-Mitric** [comment]
#235

**Comment by Stefan-Mitric** [comment]
fixed in Version 3.454 (Hotfix)
