### ISSUE TITLE
Turn Yaoi On/Off

### ISSUE THREAD

**Issue by BigBoobsPerv** [bunfan/beat-banger-public#24]
Not to sound rude or anything, but Ibwas wondering if there could be an option to turn the yaoi on or off with the levels that are male on male action. I'm not a fan of it at all but I do have an interest in the game and was wondering if that could be made an option. I was just thinking of the option being put into the settings menu and what happens is the levels would be either skipped entirely or not contain the yaoi.

**Comment by komdog** [comment]
Considering the game is highly modifiable, this feature will most likely not be added.
