### ISSUE TITLE
Game starts on secondary monitor by default (v3.452)

### ISSUE THREAD

**Issue by Sebishosho** [bunfan/beat-banger-public#240]
### Discord Tag

@sebishosho

### Issue Description

I don't know if it has anything to do with the fact that it says "(DEBUG)" on the top-left corner, but it's a bit annoying having to drag the window to my main monitor and switch back to fullscreen mode every time.
![Screenshot 2024-02-15 024659](https://github.com/bunfan/beat-banger-public/assets/160104971/ee254f4f-8c4c-47f6-8934-54675bde09c2)

### OS

Windows

### Version

3.34 dev1 (Steam)

**Comment by Stefan-Mitric** [comment]
Unable to reproduce. Will reopen if issue recurs.

**Comment by DoodleSurf** [comment]
If you manage to get back to this topic - try switching over to your primary monitor by using the `WIN + P` combiation to force game off the second monitor. This might help you solve the issue on your setup.
