### ISSUE TITLE
Gale small errors

### ISSUE THREAD

**Issue by Yungdeag** [bunfan/beat-banger-public#244]
### Issue Description

Gale still seems to be missing her open_mouth moans, simply needs
"voice_bank": [{
"timestamp": 0.0,
"voice_paths": ["gale_open_moan_1.ogg", "gale_open_moan_2.ogg", "gale_open_moan_3.ogg", "gale_open_moan_4.ogg", "gale_open_moan_5.ogg"]
}, {
added to keyframes. 

Also seems to have feet cutoff during gale_pussyfuck

### OS

Windows

### Version

3.452 (Steam)

**Comment by Stefan-Mitric** [comment]
#125

**Comment by komdog** [comment]
Duplicate of #125
