### ISSUE TITLE
Tiny detail with new claire imageset

### ISSUE THREAD

**Issue by Yungdeag** [bunfan/beat-banger-public#245]
### Issue Description

During Claires new buttdrum, the different tone on her arm isn't present
![Missingtone](https://github.com/bunfan/beat-banger-public/assets/149015701/d24f8168-6052-4b23-bcb8-04b8cd59ed94)

### OS

Windows

### Version

3.452 (Steam)

**Comment by 1MPexe** [comment]
This will be fixed in the newest update.
