### ISSUE TITLE
mod acts selection index doesn't update properly

### ISSUE THREAD

**Issue by DoodleSurf** [bunfan/beat-banger-public#247]
### Discord Tag

@doodle2315

### Issue Description

When selecting an act of a mod - MenuCache.mod_level_menu_index doesn't get updated properly. (3.454 Hotfix)
Video: https://github.com/bunfan/beat-banger-public/assets/133990496/44323669-791a-4acf-b8c5-e08833ede92d

### OS

Windows

### Version

3.452 (Steam)

**Comment by 1MPexe** [comment]
Could this be mod specific?

**Comment by DoodleSurf** [comment]
> Could this be mod specific? I can't seem to replicate this with other mod packs.

No, it's present in every mod with multiple acts.

**Comment by Stefan-Mitric** [comment]
the best mod to test it on is this: https://bbooru.fun/post/1104
has two different level with three difficulties

**Comment by komdog** [comment]
Should be fixed in 3.455
