### ISSUE TITLE
Gale's code missing voice cue?

### ISSUE THREAD

**Issue by wildcard47** [bunfan/beat-banger-public#248]
### Discord Tag

@wildcard47

### Issue Description

In the keyframes section of code, the "voicepaths" only uses the "gale_quick_moan" audios for the entire duration of the song, and does not use any of the "gale_open_moan" audios. I wasn't sure if this was intentional or not but thought I would bring it to yall's attention

### OS

Windows

### Version

3.452 (Steam)

**Comment by hackerTiger21** [comment]
#244

**Comment by Stefan-Mitric** [comment]
#125

**Comment by komdog** [comment]
Duplicate of #125
