### ISSUE TITLE
Ghost Notes are broken on controller

### ISSUE THREAD

**Issue by yukiami** [bunfan/beat-banger-public#249]
### Discord Tag

@yukiami

### Issue Description

Ghosts notes don't appear as they should when using a PS controller.

This is what they should look like:
![20240215051832_1](https://github.com/bunfan/beat-banger-public/assets/160106975/a4ee9628-26c3-42b9-8456-cf7d4065c095)

This is what they do look like:
![20240215021548_1](https://github.com/bunfan/beat-banger-public/assets/160106975/8e3cf472-f210-4fb6-b716-6c846b6e3c02)

### OS

Windows

### Version

3.452 (Steam)

**Comment by yukiami** [comment]
issue exists with xbox controller inputs as well 
![20240215175358_1](https://github.com/bunfan/beat-banger-public/assets/160106975/9e17a680-21a1-4da0-8efc-310edd3189b1)

**Comment by komdog** [comment]
This issue will be fixed and push in 3.46
