### ISSUE TITLE
Bug on Option Menu

### ISSUE THREAD

**Issue by Ratzius** [bunfan/beat-banger-public#25]
**Describe the bug**
It's a small visual bug where the Option Menu slides down.

**To Reproduce**
1. Go to 'Option'
2. Change the Setting from from right to left like = Game -> Audio ->Game -> Audio ->Game
3. Sometimes it  slides to much down the screen.
4. It happens on every Option Menu. Game/Audio,  Audio/Keybinds,  Keybind/Video and Video/Game.

**Expected behavior**
It could be that the code puts a wrong value for position or a wrong value for the anmation so it jumps down on the wrong screen position.

**Screenshots**
Video of the Bug down below

**Desktop (please complete the following information):**
 - OS Name: Microsoft Windows 11 Home
 - Version	10.0.22000 Build 22000
 - Game: Latest patreon version

**Additional context**
[Bug on Option.webm](https://github.com/bunfan/beat-banger-public/assets/117361631/9dd3e7c4-0890-4287-92c7-8e387e45fc6f)

If you can look up the video text me via: Discord = ratzius. (I already have you as a friend in discord just to now).

**Comment by komdog** [comment]
Options menu has been completely reworked
