### ISSUE TITLE
Multi-level mods are broken (3.454)

### ISSUE THREAD

**Issue by AlexVII7** [bunfan/beat-banger-public#253]
### Discord Tag

alex_vii

### Issue Description

If the mod has multiple levels the game only loads the one the one with the lowest level_index, no matter what you select.
https://github.com/bunfan/beat-banger-public/assets/140367896/a35c5dd5-1c4f-4a56-8732-f9a8615c68e2

### OS

Windows

### Version

3.452 (Steam)

**Comment by DoodleSurf** [comment]
Thank you for the report! This is an ongoing issue. #247
