### ISSUE TITLE
So uh when will the mods will stop resetting

### ISSUE THREAD

**Issue by LiamVickerss** [bunfan/beat-banger-public#256]
### Issue Description

how many times this happened uh 3 or maybe was it the 4th time all the mod just get reseted after a update. any update big or small. Like ı am so tired and sick of it just bring back no fail mode saving the mod to ease the pain at least? but no i have to replay pretty much the entire release mods that ever created to get 5-6-7 starts on all of them again? please just just bring back the no fail mode saving progress at least that would ease the pain a bit but please stop resetting all the mod progression resetting after a update or i will just stop updating the game forever or just straight up delete it now never redownload it again.

### OS

Windows

### Version

3.455 (Steam)

### Relevant log output

```shell
what idk what it says here my english is not that great idk what revelant log outpıt means but its prob means the error crash screen you get when your game crashes.
```

**Comment by DoodleSurf** [comment]
The latest patch introduced the hash system that should prevent the save file reset during the future updates.
In the meantime - you can possibly recover and edit the save file by editing the `game.sav` file with the notepad. 

You can get to it by either going into the `C:\Users\Your_Name\AppData\Roaming\Godot\app_userdata\Beat Banger` or by typing in-game's `F2` console `open save`
