### ISSUE TITLE
Low Quality MacOS Window

### ISSUE THREAD

**Issue by KirbyKid256** [bunfan/beat-banger-public#26]
**Describe the bug**
So unlike most other macOS apps, not only does Beat Banger not allow hiDPI for Retina displays, but the border for the window itself is also lower quality than most other applications.

**Screenshots**
The first screenshot is of the official build of the game. The second one is of a modified build me and Doodle have been working on. Both of these screenshots are the exact same window size, but different resolutions. 
![Window_Type1](https://github.com/bunfan/beat-banger-public/assets/70983335/08b57458-a359-4230-ad52-b6c98731d661)
<img width="1348" alt="Window_Type2" src="https://github.com/bunfan/beat-banger-public/assets/70983335/894be52d-0aea-4e2b-b1a7-3cc74c04090a">
In the project settings of the build, I turned on "Allow hiDPI" under `display/window/dpi/allow_hidpi`. And while I haven't exported this one for macOS, I have for my modified BB Charter where I turned on "High Res" in the export menu under `display/high_res` for the macOS export preset which fixed the border problem.

**Desktop**
 - OS: macOS Ventura
 - Version: v2.9

**Additional context**
Before you ask, yes I did try using override.cfg, and I did place it right next to the data folder and Unix Executable, it had no effect. I even tried putting the project setting override in the pck code and it still didn't do anything.

**Comment by KirbyKid256** [comment]
So follow-up, I've noticed that in full screen with hiDPI, there's lag in areas like the Mods Menu and during gameplay. I left this alone and wanted to find SOME way to toggle hiDPI, but Doodle found this and shared it with me from one of the Godot docs
![image](https://github.com/bunfan/beat-banger-public/assets/70983335/575eafbd-9801-45c8-9983-6c4c47f7ad13)
So yeah, don't add this to the game because there's no way to overwrite it externally. The only thing I could recommend is adding smaller resolutions for hiDPI displays like mine just so the window doesn't go offscreen.

**Comment by komdog** [comment]
This should be fixed 👍
