### ISSUE TITLE
App crashes if i try to Connect to Lovense

### ISSUE THREAD

**Issue by Felidea** [bunfan/beat-banger-public#262]
### Discord Tag

Felinyara

### Issue Description

Hello!

If i try to connect my Lovense on PC (App is in Mobile) it crashes when i click at Connect. Thats... all. 

I tried to run the file as Admin and stuff, but it keeps crashing. I use the Patreon-Version of the Game!

### OS

Windows

### Version

3.455 (Steam)

**Comment by Stefan-Mitric** [comment]
Provide us with an recording please

**Comment by Felidea** [comment]
If you could tell me how please!

**Comment by Stefan-Mitric** [comment]
You install OBS Studio. Here is the Link = https://obsproject.com/de/download
You can look up some tutorials on YouTube and the send the video

**Comment by Felidea** [comment]
https://github.com/bunfan/beat-banger-public/assets/82948428/1b915850-b5b6-4e8c-9611-df3c3950be92

Here it is!

**Comment by 1MPexe** [comment]
Could you post logs?

**Comment by JohnSmith2007** [comment]
It doesn't even let me access the menu. As soon as I try to access it, it crashes to the desktop.

**Comment by hackerTiger21** [comment]
Hm, bit of a Hail Mary here, what are the values of `"lovense_ip"` and `"lovense_port"` in your `settings.sav` file?

**Comment by LobotomyCore** [comment]
I'm having this issue and I noticed that It only crashes after connecting to the mobile app. Putting in the wrong ip or not having the app open on my phone both don't crash the game. The app also reports the game connecting.



> Hm, bit of a Hail Mary here, what are the values of `"lovense_ip"` and `"lovense_port"` in your `settings.sav` file?

Where is this file?

**Comment by hackerTiger21** [comment]
@LobotomyCore 
Windows path: `C:\Users\<username>\AppData\Roaming\Godot\app_userdata\Beat Banger\`
Linux path: `~/.local/share/godot/app_userdata/Beat Banger/`

However, that thing you mentioned is interesting. It *only* crashes after connecting to the mobile app?

**Comment by LobotomyCore** [comment]
@hackerTiger21 Yeah, to the point where if I can crash the game remotely from my phone just by connecting to the ip in-game before going into game mode in the app. When I open game mode it auto-connects and crashes without me touching the computer.

**Comment by DoodleSurf** [comment]
The bug of Lovense menu crashing has been identified, the issue has been forwarded to the dev team.

**Comment by DoodleSurf** [comment]
Should be fixed in 3.481 hotfix.
