### ISSUE TITLE
BeatBanger crashing on startup

### ISSUE THREAD

**Issue by BillNy3Sov1etSpy** [bunfan/beat-banger-public#263]
### Discord Tag

@billny3sov1etspy

### Issue Description

Currently, every time I've tried opening the game, it opens on the wrong monitor, and then all I get is a black screen, nothing happens. I've tried taking all the mods out of the mods folder, I've tried verifying the integrity of game files through steam, I've even tried deleting and reinstalling the game but nothing seems to have worked.

### OS

Windows

### Version

3.455 (Steam)

**Comment by BillNy3Sov1etSpy** [comment]
*UPDATE*
Have looked at Troubleshooting FAQ on Discord and have followed procedure for Nvidia graphics, didn't work. Tried updating graphics drivers, still didn't work

**Comment by Stefan-Mitric** [comment]
#234
