### ISSUE TITLE
Grey screen and not showing up.

### ISSUE THREAD

**Issue by sausagefruit** [bunfan/beat-banger-public#265]
### Discord Tag

@sausagefruit 

### Issue Description

I recently bought the game and it's my first time running it, when I launch the game on Steam it shows the loading screen then disappears, when I hover over the tab it shows a grey screen, and clicking on it does nothing.

### OS

Windows

### Version

3.455 (Steam)

**Comment by Stefan-Mitric** [comment]
Give is more information about your set up. Do you use 2 Monitor?

**Comment by sausagefruit** [comment]
Hello, I was able.to fix the issue with some more looking into the discord
pins.

**Comment by Stefan-Mitric** [comment]
fixed
