### ISSUE TITLE
Latence, sound crackling and slow climax scenes

### ISSUE THREAD

**Issue by warforge2001** [bunfan/beat-banger-public#266]
### Issue Description

Music crackles (latency) as if having perfomance issues, then go back to normal. It happens randomly at every part of the application (menu, in-game, options, etc). Sometimes music begins to get slow and the game gets slower for maybe 10-15 seconds and back to normal. It happens once or twice in about a minute. Also climax scenes always run slow.

I've tried all possible options available (refresh rate, resolution, aspect ratio, display mode, etc) with no results.

### OS

Windows

### Version

3.455 (Steam)

**Comment by Stefan-Mitric** [comment]
Do you use Windows 10?

**Comment by Stefan-Mitric** [comment]
#228
