### ISSUE TITLE
Not seeing score

### ISSUE THREAD

**Issue by JacktheReaper29** [bunfan/beat-banger-public#267]
### Discord Tag

@Hallowguy

### Issue Description

Hello and good evening,

When playing a mod with a single difficulty it will play the level without you choosing that difficulty and not show your score after completing the level.

Example is the below screenshot.

![Screenshot 2024-02-25 160424](https://github.com/bunfan/beat-banger-public/assets/161256861/449d7327-e567-4421-8bec-0a00cab82f43)

Thank you for your time,

Hallowguy

### OS

Windows

### Version

3.455 (Steam)

**Comment by Stefan-Mitric** [comment]
What does your version number display in the bottom left corner?

**Comment by Stefan-Mitric** [comment]
I think he has an older version of the game and hasn't updated it or he has an older version of itch
