### ISSUE TITLE
the type of music you choose for the title doesnt save after you quit

### ISSUE THREAD

**Issue by Brickbronze654** [bunfan/beat-banger-public#268]
### Discord Tag

Brickbronze654

### Issue Description

don't know if someone already reported this but, once you go to extras and change the type of music that plays in the title and then once u quit the game and come back the music that you choose won't be the one playing, don't know if it's just me or if this is happening to everyone else.

### OS

Windows

### Version

3.455 (Steam)

**Comment by Stefan-Mitric** [comment]
Its not a bug.
