### ISSUE TITLE
Game won't start, only a black screen shows up

### ISSUE THREAD

**Issue by Rallve** [bunfan/beat-banger-public#269]
### Discord Tag

@rallve

### Issue Description

I just bought the game and it won't boot properly. Only a black screen shows up (not even on my primary monitor for whatever reason) and nothing else happens. I've tried to restart it multiple times, verified game files on Steam, rebooted my PC, reinstalled the game, running it as administrator, but nothing works. Apparently some other folks have had the same issue on the Steam discussions page.

### OS

Windows

### Version

3.455 (Steam)

**Comment by DoodleSurf** [comment]
check for these:
- Disable any overlays from third party apps (Razer, Motherboard Related Apps from MSI/Asus), their aggressive hook-ups to apps can prevent the game from launching.
- Set to default any settings in the Nvidia/AMD graphics panel (Forced anti-aliasing and AO tends to crash Godot Engine)
- Try to disable secondary monitor and launch the game
- Try to launch the game with these startup flags/arguments `--rendering-driver opengl3 --audio-driver Dummy`. Here's an example on how it can look in Steam.
- if the game launches with `--audio-driver` flag, that means there's something conflicting with your audio system. Usually that means that you need to set a certain audio channel *(some headsets have secondary channel for Chatting, which works in limited Mono type, which the game doesn't support, and the OS can set that channel as your default playback device)* as your default playback device in the Control Panel --> Sound. 
- if the game launches with `--rendering-driver` that means your hardware is on a low end and doesn't support Vulkan based graphics, no worries - the game should work as is.
![image](https://github.com/bunfan/beat-banger-public/assets/133990496/e3c57f25-0bbd-484d-a415-8cf0e1f29bcc)

**Comment by Rallve** [comment]
I managed to launch the game, but it only works if my secondary monitor is disabled. At least I can play the game now, but I still hope this weird bug gets fixed.

**Comment by Stefan-Mitric** [comment]
#265
