### ISSUE TITLE
Lovense won't connect

### ISSUE THREAD

**Issue by HatiSol** [bunfan/beat-banger-public#27]
**Describe the bug**
Lovense wont connect

**To Reproduce**
Go to options -> Lovense -> input IP and Port -> click connect

Nothing happens when I hit connect.
**Expected behavior**
Added in the IP and port as per normal but it never connects to any of my devices.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version v2.9 (steam)

**Comment by komdog** [comment]
This issue has been fixed
