### ISSUE TITLE
Hidden Notes Missing For Controller UI

### ISSUE THREAD

**Issue by MsArcticFoxy** [bunfan/beat-banger-public#272]
### Discord Tag

@MsArcticFoxy

### Issue Description

Upon playing Gale's Expert, I ran into an issue with the UI. I noticed that the UI for keyboard there were like... new "type" of keys/notes that upon having the controller UI wasn't present. Randomly I started getting notes wrong when having the controller UI and was confused because I knew and saw that I was hitting the correct notes at the correct times. Thankfully I remembered seeing the new type of notes for the keyboard UI and realized there were notes visually missing for the Controller UI. It has the glow of the note, but the note itself is missing.

![controller_ui](https://github.com/bunfan/beat-banger-public/assets/91772233/4d538501-63f1-4c3a-9e95-57fe2145ebec)
![keyboard_ui](https://github.com/bunfan/beat-banger-public/assets/91772233/7b7f5f12-a7d1-49b3-b4cd-0d3616be7517)

### OS

Windows

### Version

3.455 (Steam)

**Comment by MsArcticFoxy** [comment]
Interesting... Upon plugging my controller back in, the notes appeared.

![controller_ui-2](https://github.com/bunfan/beat-banger-public/assets/91772233/1a9fa993-e205-4780-b14d-011f708ee1e1)

**Comment by MsArcticFoxy** [comment]
However, it seems upon restarting... The notes disappear again.
![controller_ui-3](https://github.com/bunfan/beat-banger-public/assets/91772233/3dde0946-2c05-4603-879f-046640d4e17e)

**Comment by 1MPexe** [comment]
Issue will be fixed in the next update.
