### ISSUE TITLE
The mods not display

### ISSUE THREAD

**Issue by wiskats** [bunfan/beat-banger-public#273]
### Issue Description

When i select mods option, the game close. 

### OS

Windows

### Version

3.455 (Steam)

**Comment by DoodleSurf** [comment]
Check for `beatbanger.log` in the `C:\Users\YOU\AppData\Roaming\Godot\app_userdata\Beat Banger\logs`
We've had a recent wave of users reporting on the same issue and the main suspect for everybody has been Tails Mod.
It contains a corrupted `splash.png` file that you can remove to alleviate the issue.

**Comment by komdog** [comment]
It should be fixed as of 3.482
