### ISSUE TITLE
Bugged zoe achievement

### ISSUE THREAD

**Issue by Yungdeag** [bunfan/beat-banger-public#274]
### Issue Description

Upon completeing zoe's level without dropping combo, didn't seem to be unlock the "Eyes up here" achievement. Using the Itchio version
![Ach](https://github.com/bunfan/beat-banger-public/assets/149015701/6382a406-ba64-4411-8b79-5b3ce1c91210)
![Lvl](https://github.com/bunfan/beat-banger-public/assets/149015701/8c6e2a9d-1b35-40f0-a825-2621e8505efb)

### OS

Windows

### Version

3.455 (Steam)

**Comment by 1MPexe** [comment]
Fixed in most recent update.
