### ISSUE TITLE
Half ghost notes in every expert level but Cathy's.

### ISSUE THREAD

**Issue by Shmohawke** [bunfan/beat-banger-public#275]
### Issue Description

Button icons missing in specific areas on every expert level. Not that many, usually just one line of notes per each level.

The previous version seemed to have ghost notes that were fully gone and unhittable. These ones show a light color and color circle, but the actual button icon is missing. 

The notes themselves are hittable and fine when you hit them on time. It seems to be more of a visual error.

### OS

Windows

### Version

3.455 (Steam)

**Comment by DoodleSurf** [comment]
Please check again, the bug supposed to be fixed in `3.48`

**Comment by Shmohawke** [comment]
double checked and took screens. also forgot to mention I'm using a ps4 controller 
![snapex1](https://github.com/bunfan/beat-banger-public/assets/161905459/413ea2ef-ccb0-4eda-874f-5b9b38b3bca5)
![snapex2](https://github.com/bunfan/beat-banger-public/assets/161905459/02083e5c-f79d-4963-9781-af36c3a878d2)
![snapex3](https://github.com/bunfan/beat-banger-public/assets/161905459/74ae6023-8869-470c-8e2e-77f803bb8cf7)

**Comment by 1MPexe** [comment]
controller visuals fixed & ghost notes added to cathy's level.
