### ISSUE TITLE
love scence

### ISSUE THREAD

**Issue by kaizen1234321** [bunfan/beat-banger-public#276]
### Issue Description

whenever i try to use the lovescence connect, it either wont connect at all or crash the game in the process of trying to connect

### OS

Windows

### Version

3.455 (Steam)

**Comment by hackerTiger21** [comment]
#262

**Comment by DoodleSurf** [comment]
Should be fixed in 3.481 hotfix.

**Comment by DoodleSurf** [comment]
Closing for duplicate issue.
