### ISSUE TITLE
Lovense crashes the game

### ISSUE THREAD

**Issue by Keelut88** [bunfan/beat-banger-public#278]
### Discord Tag

@keelut

### Issue Description

Game crashes and closes when attempting to connect lovense toys.

### OS

Windows

### Version

3.455 (Steam)

**Comment by hackerTiger21** [comment]
#262

**Comment by DoodleSurf** [comment]
Should be fixed in 3.481 hotfix.

**Comment by DoodleSurf** [comment]
Closing for duplicate issue.
