### ISSUE TITLE
Controler bug

### ISSUE THREAD

**Issue by laryssaneko** [bunfan/beat-banger-public#28]
**Describe the bug**
basicly, i just downloaded the game and it came with the features of controler, such as starting with ABXY (while i don't have a controler and i have only my keyboard)

**To Reproduce**
I just downloaded the game

**Expected behavior**
i opend the game and it started that way

**Screenshots**
![image](https://github.com/bunfan/beat-banger-public/assets/139415795/8568190e-f952-46b8-bc91-006cbc885b42)
![image](https://github.com/bunfan/beat-banger-public/assets/139415795/c01155c5-73a1-4003-bbba-16b246c8a93a)

**Desktop (please complete the following information):**
 - windows 10
 - Version [Latest version

**Additional context**
would be great if you added a way to change between controler and keyboard

**Comment by komdog** [comment]
Odds are you have some sort of device plugged in that is registering as an Xbox Controller or X input controller. Try unplugging your USB devices and seeing if you get the same result.

Either way, this issue should be fixed when we push the next public build.
