### ISSUE TITLE
Ghost notes on the bottom bar

### ISSUE THREAD

**Issue by Nato1ess** [bunfan/beat-banger-public#280]
### Discord Tag

@Natoless

### Issue Description

Some notes on the bottom bar are shown incorrectly in Zoe's, Gale's and Claire's expert level.
The type of ghost note as the second video only shows up on Zoe's level
This is the v3.481 version on steam.

https://github.com/bunfan/beat-banger-public/assets/148785867/a0662d6a-32dd-4822-8aad-3c4d29deaa35

https://github.com/bunfan/beat-banger-public/assets/148785867/2a2312f1-f327-444e-80eb-f5317b17913b

### OS

Windows

### Version

3.455 (Steam)

**Comment by 1MPexe** [comment]
The white notes are automatic note that do not need to be hit. Can you explain what you mean in greater detail?

**Comment by Nato1ess** [comment]
I thought the white notes just didn't show what you're supposed to press, since I even got a 'Great' rating in the second last one in the video.
Thanks for the explanation

**Comment by Nato1ess** [comment]
I see, then it was a false bug report.
