### ISSUE TITLE
Is this intentional

### ISSUE THREAD

**Issue by Shadowyt2020** [bunfan/beat-banger-public#282]
### Discord Tag

shadowmusic

### Issue Description

I started just messing around and hit the the key in the arrow sequence like up, down, up ,down and so on and this appeared. I
 don't know if this is intentional or not, I just thought i should bring it up 
![Screenshot 2024-03-07 195759](https://github.com/bunfan/beat-banger-public/assets/162561231/85e4bd60-5f79-4e20-bd0c-523d45d130b0)

### OS

Windows

### Version

3.482

**Comment by 1MPexe** [comment]
This is not a bug.
