### ISSUE TITLE
Xbox Controller not compatible with Legacy mods

### ISSUE THREAD

**Issue by revfanboy** [bunfan/beat-banger-public#288]
### Discord Tag

@joetheokay

### Issue Description

I redownloaded the game because I wanted to play all the old Legacy content on my steam version of the game. But when the first wave of notes appeared, they looked like little place holders or =s (shown below)
![Screenshot (12)]((https://github.com/bunfan/beat-banger-public/assets/26636707/46dc7626-8023-45dc-9068-52f642527fc7))
With keyboard these notes are all Vs on the default key set up. Don't know what they are supposed to be on an xbox controller though. 

### OS

Windows

### Version

3.49

**Comment by revfanboy** [comment]
Must've been an error sending the image, sending it again.
![Screenshot (12)](https://github.com/bunfan/beat-banger-public/assets/26636707/9b92135d-f646-4bcd-8a72-e06c6955a423)

**Comment by DoodleSurf** [comment]
@revfanboy Can you test this bug again? The current version of the game is 3.494

**Comment by revfanboy** [comment]
It works fine now! Thank you!

**Comment by DoodleSurf** [comment]
Fixed in preivous commits.
