### ISSUE TITLE
Not recognizing I’m using a PlayStation controller on Steam.

### ISSUE THREAD

**Issue by Neversoft9** [bunfan/beat-banger-public#29]
Playing Beat Bangers (Steam release version) with a PS5 controller but it does not recognize it, and instead gives me the Xbox buttons. 

It would help to have a setting in options to toggle what gamepad buttons players like to see. 

This bug makes the game almost non-playable for me as i’ve used a PlayStation controller, my whole life and both controllers have a blue X but they’re in different locations.

I really hope this gets fixed as I’m loving the game otherwise.

**Comment by Neversoft9** [comment]
This didn’t work. PS controller is turned on and the Xbox (Switch as well) is turned off. A option in game to pick which buttons I’d like to show up would be nice then just detecting if I’m using a PS style controller. Even if I was using a Xbox controller I’d like the the options for the PS buttons to pop up as I’m more familiar with that button layout.On Aug 18, 2023, at 3:57 PM, 5up ***@***.***> wrote:﻿
Does your PS5 Controller show up here? if it does. Disable the xbox input. if that doesn't work then idk

**Comment by DoodleSurf** [comment]
@Neversoft9 
Can you confirm if the bug persists? The currently available version that supports PS5 controllers natively is 3.13

**Comment by Neversoft9** [comment]
I’ll let you know and try it out when the update downloads on steam.On Oct 15, 2023, at 10:16 AM, DoodleSurf ***@***.***> wrote:﻿
@Neversoft9
Can you confirm if the bug persists? The currently available version that supports PS5 controllers natively is 3.13

**Comment by DoodleSurf** [comment]
@Neversoft9 The steam branch has been outdated for a while and its disabled by the project lead. Make sure to download proper patreon release.

**Comment by komdog** [comment]
The Steam version of the game will still receive updates.

**Comment by Neversoft9** [comment]
What was Doodlesurf talking about? The Steam version is out of date cause someone disabled it?On Oct 18, 2023, at 12:16 PM, KomDog ***@***.***> wrote:﻿
The Steam version of the game will still receive updates.

**Comment by komdog** [comment]
> What was Doodlesurf talking about? The Steam version is out of date cause someone disabled it?On Oct 18, 2023, at 12:16 PM, KomDog ***@***.***> wrote:﻿ The Steam version of the game will still receive updates. —Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned. Message ID: ***@***.***>

Nothing is out of date on Steam. However, The Patreon Beta build is ahead of the public release.

**Comment by Neversoft9** [comment]
Ok but I don’t know if my issue is fix yet or not as Steam does not have the new update. So I don’t know if the beta update can recognize if I have a PS5 controller on Steam or not or if I can just toggle which button layout I want to be displayed. On Oct 18, 2023, at 12:27 PM, KomDog ***@***.***> wrote:﻿
Closed #29 as completed.

**Comment by Neversoft9** [comment]
I tried it on the new update and I’m still seeing XBOX buttons, not PlayStation buttons.On Oct 18, 2023, at 12:27 PM, KomDog ***@***.***> wrote:﻿
Closed #29 as completed.
