### ISSUE TITLE
controller layout (icons) while not using controller

### ISSUE THREAD

**Issue by YenYenAst** [bunfan/beat-banger-public#296]
### Discord Tag

@padoru_nyon

### Issue Description

well when i join the game it showing me that i'm using my wireless controller (dualshock4 ps4 joystick) 
but no my controller is literally off and yeah i have to plug the controller and pull off so the game show the keybroad layout
and ofc i verified files and still the same but haven't try to reinstall 
(my game is probably corrupt or something that all my score and plays are gone but not items , threater and pictures)
maybe i'll have to reinstall 

### OS

Windows

### Version

3.49

**Comment by DoodleSurf** [comment]
Hello. What keyboard model do you have?

**Comment by Kapioga** [comment]
Checking in on this, are you still experiencing the issue after reinstalling?
