### ISSUE TITLE
Keybind UI is using controller and not keyboard UI.

### ISSUE THREAD

**Issue by Sitecrawler** [bunfan/beat-banger-public#297]
### Issue Description

Each time I open the game the user interface is using a controller layout (A, B, Y, X) and not a keyboard layout (Z, X, C, V), I reconnected my controller and then disconnected it, after that it went back to keyboard UI, but after restarting the game it goes right back to controller UI. Can there be way to chose which UI to use in the future?
![Screenshot 2024-03-18 141231](https://github.com/bunfan/beat-banger-public/assets/163931671/9291eecc-fa3e-443a-a3d2-f3aa497148c9)
![Screenshot 2024-03-18 141316](https://github.com/bunfan/beat-banger-public/assets/163931671/7a2bad40-0328-432e-8fbd-78411cf10cee)

### OS

Windows

### Version

3.49

**Comment by 1MPexe** [comment]
#296
