### ISSUE TITLE
Settings menus appearing on top of settings menu select

### ISSUE THREAD

**Issue by SkylarTheCat02** [bunfan/beat-banger-public#298]
### Discord Tag

skylarthecat

### Issue Description

I just installed some mods to play, then I went to settings to adjust my volume settings. When I got to the settings menu, I noticed that it opened up game settings without me choosing it. When I looked closer it was overlayed ontop of the settings menu select screen. I exited the menu to see if it would fix itself and when I went back to settings, it put the volume settings ontop instead. Picture added for reference.
![BBbug](https://github.com/bunfan/beat-banger-public/assets/113940668/9654c36b-b1d6-4ff1-9635-792f9bd4c2ec)

### OS

Windows

### Version

3.49

**Comment by SkylarTheCat02** [comment]
Extra picture of other settings
![BBbugGame](https://github.com/bunfan/beat-banger-public/assets/113940668/0ebcc67b-4510-497d-a79b-7e9a39910512)

**Comment by SkylarTheCat02** [comment]
Okay, sorry for adding so much not in original post but I didnt think on it. It looks like it sees both menus as opened so I can interact with both menus at the same time. Even to the point to where I can have two of the different settings menus open at the same time and interact with everything at once. 
![BBbugtwoscreens](https://github.com/bunfan/beat-banger-public/assets/113940668/bef44649-c3a4-4b8a-8a78-f7332c48e2bf)

**Comment by SkylarTheCat02** [comment]
> Are you able to replicate this bug?

Yes, I found that if you open a settings tab then hit escape then go back to settings it will overlay it. You have to hit the Go Back keybind for it to actually go away.

I have a video of it but it wont let me attach to this file

**Comment by SkylarTheCat02** [comment]
https://github.com/bunfan/beat-banger-public/assets/113940668/f40257c0-4d25-4dae-bd2c-a3ecdd969cea

**Comment by Stefan-Mitric** [comment]
Fixed and has a new UI in version 3.499
