### ISSUE TITLE
Futa feature.

### ISSUE THREAD

**Issue by Breadnation** [bunfan/beat-banger-public#3]
Well if this is where a Feature request is going, I guess I'll be the first to say that there should be a *version* where each character (provided their levels character is originally female) should have Male genitalia. 
maybe something in the other direction if the character is originally a guy, I dunno as it's just a feature suggestion... not going super in depth and hopefully it wouldn't be complex.

**Comment by komdog** [comment]
Due to the **modifiable** nature of the game, things like edits to existing characters will up solely to the modding community.
