### ISSUE TITLE
Failing a mod and choosing exit, restarts the mod on controller

### ISSUE THREAD

**Issue by cursedfoxy** [bunfan/beat-banger-public#3]
**Describe the bug**
Failing a mod and choosing exit, restarts the mod on controller and keyboard.

**To Reproduce**
1. Go to 'Mods'
2. Play any 'Mod'
3. Fail level and on menu choice, hit 'exit'
4. ???
5. Profit? (The mod restarts.)

**Expected behavior**
For the level select of MODS to be visible so I can pick a different mod.

**Screenshots**
https://imgur.com/a/IbhcHpq

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version v2.892]

**Additional context**
I love the game so far, :D

**Comment by komdog** [comment]
Fixed in 2.893
