### ISSUE TITLE
Right-click in editor is not working properly

### ISSUE THREAD

**Issue by Irrelevent** [bunfan/beat-banger-public#301]
### Issue Description

When right-clicking in the level editor, the menu to change note properties only shows up when the mouse is near to either side of the screen.

### OS

Windows

### Version

3.49

**Comment by Kapioga** [comment]
Heya! 

Im unable to replicate the issue your experiencing. Could you provide a recording of what the issue looks like from your end.

**Comment by komdog** [comment]
Fixed in 3.503
