### ISSUE TITLE
keybindings

### ISSUE THREAD

**Issue by I-Riddick-I** [bunfan/beat-banger-public#303]
### Discord Tag

@_I_Shadow_I_

### Issue Description

I have changed the keybindings but when I press "Esc" there are old (stabdart) keybinding 
I dont think its a bug but anyway it can confuse someone
![1](https://github.com/bunfan/beat-banger-public/assets/103952320/04a0468f-32ed-48c9-816b-37f13bd6ad4e)
![12](https://github.com/bunfan/beat-banger-public/assets/103952320/2e9e1212-266b-428d-8551-b1254d23cefc)

### OS

Windows

### Version

3.49

**Comment by 1MPexe** [comment]
Is this bug still occurring?

**Comment by 1MPexe** [comment]
This bug seems to be fixed in our latest version.

**Comment by Stefan-Mitric** [comment]
Fixed in version 3.499
