### ISSUE TITLE
Auto failing levels

### ISSUE THREAD

**Issue by hayden679** [bunfan/beat-banger-public#304]
### Discord Tag

ennotheemmo

### Issue Description

when I start a level it is starting me in the middle of the level automatically failing me. I've tried uninstalling and reinstalling.

### OS

Windows

### Version

3.49

**Comment by 1MPexe** [comment]
Is it a specific level? or all levels.

**Comment by Kapioga** [comment]
Could you also verify if you have any modifiers active as well? Thanks!

**Comment by hayden679** [comment]
Since i just have acess to the first level right now that the only level doing it to my knowledge. I shouldn't have any mods installed either.

**Comment by Stefan-Mitric** [comment]
can you provide us with an recording?

**Comment by hayden679** [comment]
https://github.com/bunfan/beat-banger-public/assets/55631304/b75d399b-6b8a-44f5-8a27-2a33d0dc4cbc

**Comment by Kapioga** [comment]
Hi Hayden,

Im not able to recreate the issue you are experiencing within the latest Steam release. Were you downloading your copy of Beat Banger from Itch by any chance or another platform?

**Comment by komdog** [comment]
Unable to reproduce this bug. try uninstalling and re-installing
