### ISSUE TITLE
Music discs visible when you hit esc in the music section

### ISSUE THREAD

**Issue by cursedfoxy** [bunfan/beat-banger-public#306]
### Discord Tag

@cursedfoxy

### Issue Description

Music discs visible when you hit esc in the music section
![bug](https://github.com/bunfan/beat-banger-public/assets/47169904/02f0ee02-131d-4607-af5f-249c29e5deee)

### OS

Windows

### Version

3.49

### Relevant log output

```shell
None found when I copied logs :c
```

**Comment by Kapioga** [comment]
Issue resolved, please await next update for patch to apply!
