### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by g0kuuuu** [bunfan/beat-banger-public#307]
### Discord Tag

@drj4509

### Issue Description

it has not given me the option to update to the newest version of the game even though I see new versions are out.

### OS

MacOS

### Version

3.49

### Modifiers Enabled?

n/a

### What level or section is the scene present.

n/a

### Relevant log output

```shell
n/a
```

**Comment by Kapioga** [comment]
Hi G0ku,

At the moment, we are no longer supporting Mac OS. The newer versions are only available for other platforms such as Windows and Linux.
