### ISSUE TITLE
Glyph Settings do not save

### ISSUE THREAD

**Issue by KniteRite-Studios** [bunfan/beat-banger-public#309]
### Discord Tag

kniterite

### Issue Description

Hello, I noticed a bug with the newly released Input Layout Rework, Upon closing and re-opening the game, The game defaulted back to the Xbox Controller Layout.

1. Open the game
2. Select the Playstation Glyphs
3. Play a level (might not be required)
4. Close the game
5. Re open the game.

### OS

Windows

### Version

3.49

### What level or section is the scene present.

Entire Game Bug

**Comment by KniteRite-Studios** [comment]
![image](https://github.com/bunfan/beat-banger-public/assets/36118010/937941d1-6de8-4a93-b66d-9c930dc7f5b2)
I also noticed this, It would appear that the glyphs try to save, but the icons themselves dont change.

**Comment by Stefan-Mitric** [comment]
fixed in version 3.501
