### ISSUE TITLE
Black line appearing on level select screen

### ISSUE THREAD

**Issue by LorryCollu** [bunfan/beat-banger-public#311]
### Discord Tag

@LorryCollu

### Issue Description

A thin horizzontal black line appears on the level select screen when the resolution is set to native 2560x1440.
![image](https://github.com/bunfan/beat-banger-public/assets/165894133/57a16f64-cd3a-4441-bee8-d9282f840bfd)

### OS

Windows

### Version

3.5

### Modifiers Enabled?

No

### What level or section is the scene present.

PLAY > Level Selection Screen

**Comment by Kapioga** [comment]
Issue has been resolved, please wait for patch updates in the near future

**Comment by Stefan-Mitric** [comment]
fixed in version 3.501
