### ISSUE TITLE
Notes not showing up

### ISSUE THREAD

**Issue by Cathy-Smiths-Biggest-Fan** [bunfan/beat-banger-public#313]
### Discord Tag

panthom

### Issue Description

I changed my icon override to keyboard while using a controller and entered a level. When the level began, the notes were entirely hidden while the gradients above the notes were still present. I could still hit the notes and the level progressed normally (in fact, I beat it like this), but the only thing that was showing was the gradients, not the notes themselves. I can send a video of this in action if need be.

### OS

Windows

### Version

3.5

### Modifiers Enabled?

None

### What level or section is the scene present.

Cathy, on expert, entire level

**Comment by Stefan-Mitric** [comment]
Here is a preview of the visuals:

https://github.com/bunfan/beat-banger-public/assets/146543675/e7651c7f-431f-4cba-84b9-8b41bfa9bfa6

**Comment by komdog** [comment]
Fixed in 3.503
