### ISSUE TITLE
Icons in the level are not properly changing to the selected 'Icon Override' option when using a Keyboard.

### ISSUE THREAD

**Issue by Stefan-Mitric** [bunfan/beat-banger-public#314]
### Issue Description

Here is a small preview of the problem.
https://github.com/bunfan/beat-banger-public/assets/146543675/b2abafd4-f064-4bc8-b685-2f210372856a

### OS

Windows

### Version

3.5

**Comment by komdog** [comment]
Fixed in 3.503
