### ISSUE TITLE
`[<=3.501]` Menu-music and track-preview can play at the same time

### ISSUE THREAD

**Issue by foxscore** [bunfan/beat-banger-public#317]
|||
|:--|:--|
|**Discord Tag**|@fox_score|
|**OS**|Windows|
|**Version**| 3.501 *and earlier*|

### Issue Description

Custom menu-music-tracks *(selectable from `EXTRAS`>`Music`)* do not pause when entering the `PLAY` menu, causing both the menu music and the preview of the currently selected track to play at the same time.

A side effect of this is that the *"beat-circle"* around the track-selection gets triggered for the beats of both songs.

---

> [!NOTE]
> Make sure to unmute audio before pressing **play** on the video

https://github.com/bunfan/beat-banger-public/assets/30923667/8b899fea-95e9-460f-b72b-bf492101250c

**Comment by komdog** [comment]
Fixed in 3.503
