### ISSUE TITLE
`[<=3.501]` No custom music when returning from mod menu early

### ISSUE THREAD

**Issue by foxscore** [bunfan/beat-banger-public#318]
|||
|:--|:--|
|**Discord Tag**|@fox_score|
|**OS**|Windows|
|**Version**| 3.501 *and earlier*|

### Issue Description

If you return quickly enough from the `MODS` menu *(can be easily accomplished by spamming the back button)*, the menu music won't resume. This only occurs when custom menu music is selected via the `EXTRAS`>`Music` menu.

---

> [!NOTE]
> Make sure to unmute audio before pressing **play** on the video

https://github.com/bunfan/beat-banger-public/assets/30923667/80510b98-0b6a-4528-968b-e3a9ac0a5592

**Comment by komdog** [comment]
fixed in 3.503
