### ISSUE TITLE
Best combo not tracking in player stats

### ISSUE THREAD

**Issue by cursedfoxy** [bunfan/beat-banger-public#321]
### Discord Tag

@cursedfoxy

### Issue Description

Best combo in player stats not tracking. 

https://github.com/bunfan/beat-banger-public/assets/47169904/073dae1b-f271-4cb0-a1fb-ef5e08e3bd42

### OS

Windows

### Version

3.5

### Modifiers Enabled?

None

### What level or section is the scene present.

Player stats section

### Relevant log output

```shell
Logs don't give me anything?
```

**Comment by komdog** [comment]
fixed in 3.053
