### ISSUE TITLE
Error when dowloading some modes

### ISSUE THREAD

**Issue by phantomDragon533** [bunfan/beat-banger-public#323]
### Discord Tag

spade2455

### Issue Description

keep getting an error on some mods "not formatted correctly" after they've completely downloaded. I can still find the mod's zip file in the mods folder but mod did not appear after manually extracting.

### OS

Windows

### Version

3.5

**Comment by komdog** [comment]
This is on the part of the mod creator, not the game. If you wish to resolve this issue then contact the mod creator or the person who uploaded the mod to bbooru.
