### ISSUE TITLE
Auto failing levels

### ISSUE THREAD

**Issue by hayden679** [bunfan/beat-banger-public#326]
### Discord Tag

ennotheemmo

### Issue Description

Hi, I was a part of ticket #304 about auto failing levels. I meant to respond to you guys not being able to reproduce the issue I was having. I meant to respond earlier but I was on vacation and was unable to respond before the ticket was closed. I only have access to the first level and every time I have started it, it starts me in the middle of the level and automatically fails me. I originally downloaded it using the steam download on my laptop, beat a few levels, then downloaded it on my pc and it only gave me access to the first level and that's when it started auto failing me. I then tried uninstalling and reinstalling and that didn't work, I then subscribed to your Patreon and downloaded the newest version of the game then it continued auto failing me like before. I don't know what I'm doing wrong and I have no mods installed.

https://github.com/bunfan/beat-banger-public/assets/55631304/81cbf1e3-cd9a-4778-b05f-38c44793aaa3

### OS

Windows

### Version

3.5

**Comment by 1MPexe** [comment]
I'm unable to reproduce this bug. Something external might be effecting your experience.

**Comment by Stefan-Mitric** [comment]
Update the game. This is what you should see in the mods section if you don't have any mods installed. If you don't see it, then you have an unsupported mod in the folder, deleted the mod and try a level again.
![image](https://github.com/bunfan/beat-banger-public/assets/146543675/d2dfdda0-382f-4f53-b4a1-a44466521db8)
