### ISSUE TITLE
FPS inestables

### ISSUE THREAD

**Issue by JosshuaCS** [bunfan/beat-banger-public#327]
### Discord Tag

josshua203

### Issue Description

al momento de entra al juego tengo una caida de fps muy baja de uno 5 y eso no me pasaba antes al jugar antes era de 30 fps o mas pero no se que paso que ahora son solo abrir el juego corre 5 fps no puedo selecionar un mapa o muscia para jugar no se si es porblema de los mods que no medija jugar pero antes no pasaba eso o fue la atulisacion que coropio todo mi dato de juego como los mods que instale estan coropidos
![imagen 1](https://github.com/bunfan/beat-banger-public/assets/101951554/6ff3a35b-bba2-4cd4-8dbf-d72831be135c)

### OS

Windows

### Version

3.5

### What level or section is the scene present.

del de comienso del juego cuando un no epiesa

**Comment by DoodleSurf** [comment]
¿Cuándo empezó esto y qué hardware de PC tienes?

**Comment by JosshuaCS** [comment]
ya tiene un tiempo desde la actualización de 1 de Marzo ay fu cuando el juego dejo de corre bien ya lo es instalador varia vese como 3 o 5 y nada pensado que es algo de la actualizacion pero no sige con el mismo problema mi hardware es un intel core i5 de Tercera Generación y sin trajeta grafica no se si es por el CPU viejito que el juego no me corre bien o es otra cosas y lo siento mucho por no aver contestado atienpo es que estoy ocupado en varia cosas que luego no checo mi correo esta que es lago urgente lo siento mucho 😓😓😓

**Comment by JosshuaCS** [comment]
ya entre ya que do sulusinado el ploblema gracias por la ayuda ☺
![Captura de pantalla 2024-05-05 084346](https://github.com/bunfan/beat-banger-public/assets/101951554/44867731-1645-492f-a8c0-715413aa9cbe)
