### ISSUE TITLE
In-game level creator errors with new creations

### ISSUE THREAD

**Issue by cursedfoxy** [bunfan/beat-banger-public#328]
### Discord Tag

@cursedfoxy

### Issue Description

https://github.com/bunfan/beat-banger-public/assets/47169904/96836c7e-2500-4ac5-bd20-d0d5b0a1905c

:> In-game mod creator broken?

### OS

Windows

### Version

3.5

### What level or section is the scene present.

Level Creator

**Comment by Kapioga** [comment]
Issue fixed in update 3.506
