### ISSUE TITLE
menu/scene music wierd?

### ISSUE THREAD

**Issue by LennyMcBob** [bunfan/beat-banger-public#33]
**Describe the bug**
So, the game music is fine with the raw files themselves, but in game they're very low pitch and unrecognizable. They still retain some things, but otherwise incredibly low and static-filled.

**To Reproduce**
1. I just kinda either open the game (main menu music) or go to one of the scenes (scene music) and boom.
 
**Expected behavior**
I kinda expected what was happening a couple days ago; normal music, but yesterday it decided not to anymore.

**Screenshots**
screenshots don't help, will try to add sound files later.

**Desktop (please complete the following information):**
 - OS; Windows 10
 - Version; 2.85

**Additional context**
not much, modded songs are fine and i'm using the steam version.
EDIT; so it's ALL pre-existing game sound effects now, and one or two mod songs have gone dead. Cant conform about the modded songs rn but will check

**Comment by komdog** [comment]
This bug only happens on a specific set of headphones. We've ported the game to the newest version of Godot (4.2 dev3), so hopefully, that will fix the problem.
