### ISSUE TITLE
Horny Notes and Transitions Clashing.

### ISSUE THREAD

**Issue by Ozrenol** [bunfan/beat-banger-public#332]
### Discord Tag

.lorenzo.il.magnifico.

### Issue Description

If a transition note is also the last of a horny string, the transition will be ignored and instead play the previous loop's horny alt.

https://github.com/bunfan/beat-banger-public/assets/134641266/66927074-9ba3-4a1e-a5bd-058355cf48f4

### OS

Windows

### Version

3.5

### Modifiers Enabled?

None.

### What level or section is the scene present.

Found in a mod level, as official level don't use horny notes yet.

**Comment by 1MPexe** [comment]
is this issue still occurring?

**Comment by Stefan-Mitric** [comment]
Does not occur anymore.
