### ISSUE TITLE
new update issue

### ISSUE THREAD

**Issue by omeko88** [bunfan/beat-banger-public#334]
### Discord Tag

piotrek1307

### Issue Description

ok so I don't know what happend but after update 3.512 my game started running very slowly. I have maximum of 10 fps all the time and its probably because my pc is trash but before that update every thing was fine and I had normal fps. And I know it was update 3.512 that cause it because I played the day when update 3.51 came out and the game worked normally

### OS

Windows

### Version

3.51

**Comment by 1MPexe** [comment]
Have you tried adjusting your video settings within the game?

**Comment by omeko88** [comment]
1mppexe
what do you mean?

**Comment by 1MPexe** [comment]
![image](https://github.com/bunfan/beat-banger-public/assets/89138073/476f92f6-aa0b-4fec-8b9e-ebe28a7f0ba7)
Have you fiddled with these settings?

**Comment by 1MPexe** [comment]
Is this issue still occurring?
