### ISSUE TITLE
Exiting the cutscene through hotmenu does not reset the scene count

### ISSUE THREAD

**Issue by DoodleSurf** [bunfan/beat-banger-public#335]
### Discord Tag

@doodle2315

### Issue Description

Exiting the cutscene through the hotmenu affects the global cutscene frame counter, spilling into other levels.

https://github.com/bunfan/beat-banger-public/assets/133990496/064cd4cb-959a-4153-831e-f36e0d4cf476

### OS

Windows

### Version

3.51

### Modifiers Enabled?

None

**Comment by komdog** [comment]
Fixed in 3.513
