### ISSUE TITLE
Opening Esc menu in shop

### ISSUE THREAD

**Issue by imonred** [bunfan/beat-banger-public#336]
### Discord Tag

yunomong

### Issue Description

When the "escape" or pause menu (or whatever it's called) is open, the "voice"/sound of Jasmine's dialogue idly changing is clearly audible over the muffling sound filter that is put on the music

### OS

MacOS

### Version

3.51

### What level or section is the scene present.

Shop

**Comment by komdog** [comment]
Fixed in 3.513
