### ISSUE TITLE
Controller causes game to freeze

### ISSUE THREAD

**Issue by cadooron2** [bunfan/beat-banger-public#339]
### Discord Tag

@nighttragon

### Issue Description

Like the title says, whenever i plug in a PS controller (PS4 or PS5) the game freezes and continues after a minute or 2 without recognizing the controller.
I managed to play the game with a controller earlier but now it just stopped.

### OS

Windows

### Version

3.51

### What level or section is the scene present.

Game itself

**Comment by 1MPexe** [comment]
I can't seem to replicate this bug. Could you present your log output?
