### ISSUE TITLE
Expert Difficulty Game Closing itself

### ISSUE THREAD

**Issue by dyland17** [bunfan/beat-banger-public#349]
### Discord Tag

fallenangel25

### Issue Description

Well I was playing Cathy and Claire's levels on expert. After a minute or two it would close the game itself. I just wanted to try the new notes you guys implemented.

### OS

Windows

### Version

3.51

### Modifiers Enabled?

No modifiers as far as I know.

### What level or section is the scene present.

A minute of playing Cathy or Claire's levels on Expert.

**Comment by Stefan-Mitric** [comment]
fixed in version 24w30d
