### ISSUE TITLE
Does not work on Steam Deck

### ISSUE THREAD

**Issue by PhoenixAdverdale** [bunfan/beat-banger-public#35]
The game cannot get past the title screen on Steam Deck

1. Open game
2. Says press A to continue
3. Does not work

I was hoping to open the gamne? Github telling me how to format this is weird

Why would I need a screenshot of the pretitle

OS: Whatever Steam Deck uses, I think big picture mode, it's own OS built off of Linux (I think Vulkan)

My additional context is that there isn't really any, it sadly doesn't work on Steam Deck. I would love to play it on Steam Deck but it sadly doesn't. Hope this gets fixed!

Here's a link to a google drive video of the problem, recorded on my beautiful phone lmao
https://drive.google.com/file/d/1QinHRmSk4JqaBHCPT26S-qVMr3Q0ZpP2/view?usp=sharing

**Comment by PhoenixAdverdale** [comment]
The current layout is the default layout, the official layout. My steam deck is updated to the current version, last checked 2 hours ago. I am on the stable branch of my steam deck. I also reinstalled the game and it did not fix it.
![20230818_190101](https://github.com/bunfan/beat-banger-public/assets/142633754/c5d2cbc0-5e7f-47c8-ad40-385d259df256)
![20230818_190146](https://github.com/bunfan/beat-banger-public/assets/142633754/be4da0ba-25db-4b0a-bd8c-a3d206da9e14)

**Comment by PhoenixAdverdale** [comment]
The keyboard and mouse did also not work. My Steam deck works for other games like lost in vivo and bloons TD 6 without issue at all. I did the test and it was fine, nothing wrong. It says Test Complete, what now?

**Comment by PhoenixAdverdale** [comment]
Did nothing, yippee. This seems like a problem on the games end tbh, has anyone else tested on steam deck before?

**Comment by PhoenixAdverdale** [comment]
I hope they do, thanks for trying to help

**Comment by ScottCarammell** [comment]
Okay yeah, I had an issue just like this on my (Windows) PC, so this is definitely a game issue. Sometimes controller input just doesn't work for an extended period of time. I found a "fix" by...not playing the game for a week or two and trying again. Yeah it sucks, and I have no idea why that happened, but that's about all I can do to help.

**Comment by komdog** [comment]
I'm curious if this is still an issue. However, we will push a new engine update soon, hopefully fixing any underlying problems with its compatibility on Steam deck.
