### ISSUE TITLE
Gale Animation Error

### ISSUE THREAD

**Issue by FlappyBoi032** [bunfan/beat-banger-public#350]
### Issue Description

In the newest update for Beat Banger, in the Gale level her last animation phase doesn't load and stays on the current animation pose. Small error but I didn't see anyone posting about it on the Steam community page. Love the game btw!

### OS

MacOS

### Version

3.51

### What level or section is the scene present.

Present in final scene of Gale gameplay

**Comment by hackerTiger21** [comment]
Duplicate of #347
