### ISSUE TITLE
Hold Note Crash

### ISSUE THREAD

**Issue by Cathy-Smiths-Biggest-Fan** [bunfan/beat-banger-public#353]
### Discord Tag

Panthom

### Issue Description

The game will crash when I end one hold note and start another one at the same time. This can happen on Cathy's level on expert, but it is also possible to recreate the bug in the level editor with hold notes.

https://github.com/bunfan/beat-banger-public/assets/165948884/1295da42-bdf6-4b29-a153-2770071a578e

https://github.com/bunfan/beat-banger-public/assets/165948884/72db9464-05c0-4f57-b989-bfbbaa5798ac

### OS

Windows

### Version

3.531

### Modifiers Enabled?

None

### What level or section is the scene present.

Cathy expert (where it can occur naturally) and level editor 

### Relevant log output

```shell
none
```

**Comment by Stefan-Mitric** [comment]
Duplicate #349

**Comment by Stefan-Mitric** [comment]
Tested and it happens consistently.

**Comment by Stefan-Mitric** [comment]
![image](https://github.com/bunfan/beat-banger-public/assets/146543675/840e1a84-8c9b-4986-8f23-1d12695d92a1)

**Comment by atlasmjones** [comment]
I have the same issue but my analysis is different. Crashing only happens under two conditions:
1. Playing on a controller
2. Keeping the previous held note down while starting the next hold note

In other words, so long as I released the input before starting the next, it did not crash.

Additionally, these crashes did not occur when using Hands Free and I haven't replicated using keyboard controls.

**Comment by IonLord** [comment]
![image](https://github.com/bunfan/beat-banger-public/assets/166829784/7f262a48-b2ee-4f15-9bfb-a879a6589802)
Doesn't only happen with only hold notes. This also crashes the game when pressed in quick succession

**Comment by kronyx04** [comment]
at risk of being redundant
another video of the bug, slowed down and with key display
os: arch linux
https://github.com/user-attachments/assets/8fe64da0-8634-4e11-b662-6cd63d4f180a

**Comment by kronyx04** [comment]
at risk of being redundant
another video of the bug, slowed down and with key display
os: arch linux

https://github.com/user-attachments/assets/8fe64da0-8634-4e11-b662-6cd63d4f180a

**Comment by Stefan-Mitric** [comment]
fixed in version 24w30d
