### ISSUE TITLE
Beat Banger Steam Port Crashes 

### ISSUE THREAD

**Issue by MajorSquaLL** [bunfan/beat-banger-public#357]
### Discord Tag

@lazerboy1574

### Issue Description

I just recently downloaded version: 3.531. When I started playing the game, on the main campaign, beginning on the level that had Cathy on it, the game itself had a bit of lag, and then it completely crashed. 

my computer hardware specs: 
  Processor: AMD Ryzen 7 5800X 8-Core Processor    
 Graphics Card: Card name: AMD Radeon RX 6700
memory: 64RAM

### OS

Windows

### Version

3.51

### What level or section is the scene present.

Present in Cathy

**Comment by MajorSquaLL** [comment]
Here's the recording of the game play on my end, your team needs to update it. 

https://github.com/bunfan/beat-banger-public/assets/172101931/05b62382-7407-4dc4-9538-b9547b7c9226

**Comment by Stefan-Mitric** [comment]
Duplicate #349
