### ISSUE TITLE
Changing transition sound and toggling transition flash

### ISSUE THREAD

**Issue by Odalys-Goathoof** [bunfan/beat-banger-public#36]
The transition between sections is pretty jarring - a white flash with a noisy sound. I understand that it's there to hide the change of animation, but the flash can be too bright when playing at night and the transition sound becomes stale after playing a lot of levels.

I'd like for the chart to dictate what sound to use for the transition, as well as whether to show the flash or not.
This would allow modders to spice up the transition sounds or possibly silence them for better immersion.
Disabling the flash would let modders make their own transitions (like a 1-beat loop of going from one position to another) and possibly even 12-frame loops.

Alternatively, the option to turn off the sound and flash in the in-game options would solve the problem without the need for a player to go into charts.

**Comment by komdog** [comment]
Added in v0.04
