### ISSUE TITLE
Crash Bug

### ISSUE THREAD

**Issue by MixToaster** [bunfan/beat-banger-public#361]
### Discord Tag

@mixtoaster

### Issue Description

Whenever I updated the game it would crash whenever I started playing. I even reset my data, setting, and uninstalled and reinstalled the game, but no change.

https://github.com/bunfan/beat-banger-public/assets/136585769/d13c367c-b7f5-4ac6-814a-4316c2c30c1a

### OS

Windows

### Version

3.51

### Modifiers Enabled?

None

### What level or section is the scene present.

Unknown

**Comment by Stefan-Mitric** [comment]
Duplicate #349
