### ISSUE TITLE
Sudden shutdown problem

### ISSUE THREAD

**Issue by kr3by4** [bunfan/beat-banger-public#364]
### Discord Tag

@ayberk8888

### Issue Description

https://github.com/bunfan/beat-banger-public/assets/172422674/ecf2a45d-441f-4802-8258-84d4956fe226

It suddenly shutting down. I think the problem occurred when I pressed the "c" key and then pressed the "z" key without releasing the "c" key.

### OS

Windows

### Version

3.51

**Comment by Stefan-Mitric** [comment]
Duplicate #349
