### ISSUE TITLE
Crash pesistent on hold note levels

### ISSUE THREAD

**Issue by FurSwapCharaOFFICIAL** [bunfan/beat-banger-public#365]
### Discord Tag

(Display name: Paincat) @RealFurSwapChara 

### Issue Description

midway through the chart, the whole game freezes and crashes soon after. I have no idea why it's happening, and it's ONLY on Expert. both Normal and Virgin are doable and don't activate the bug.

### OS

Windows

### Version

3.531

### Modifiers Enabled?

None

### What level or section is the scene present.

Any stage with consecutive holds / holds right after notes

**Comment by FurSwapCharaOFFICIAL** [comment]
I found how it happens. apparently, hitting a hold note after a note sometimes crashes the game??????
I don't know HOW this works, but please do testing by trying this out on Cathy - Expert and Zoe - Expert. I dunno what else to say other than playtest and find out why it happens.

**Comment by Stefan-Mitric** [comment]
Duplicate #349
