### ISSUE TITLE
Too Easy, Make Harder

### ISSUE THREAD

**Issue by SaitamaDiscord** [bunfan/beat-banger-public#368]
### Discord Tag

@saitama_2841

### Issue Description

Missing Esc menu option in the level select

### OS

Windows

### Version

3.51

**Comment by Stefan-Mitric** [comment]
what do you mean with missing. if you press ESC you get the options menu.

**Comment by SaitamaDiscord** [comment]
I mean when you are on the level select the option that lets you know that
the ESC button is to open the options menu isn't there. The option that
tells you it's there on the main menu is too transparent and not opaque
enough. Some users such as my self have slight vision issues can hardly see
it.
