### ISSUE TITLE
Cloud saves are fudged between OSs

### ISSUE THREAD

**Issue by ScottCarammell** [bunfan/beat-banger-public#37]
**Describe the bug**
Cloud saves between OSs (mainly Windows and Linux, but probably Mac too) are not compatible with one another, and as such the cloud saves don't work with one another.

**To Reproduce**
Simply attempt to cloud sync between a computer with one OS, and a computer with another (doing this with a Windows PC and Steam Deck should work just fine). 

**Expected behavior**
The save files shouldn't sync properly, unless you force the Linux computer to run the Windows version under Proton (which opens up its own issues).

**Comment by ScottCarammell** [comment]
Hey sooo I think I've found the issue and why this happens. If I'm correct, you have the Windows, Mac and Linux saves registered as separate Root Paths. This is incorrect, as root paths will not save between OSs. What SHOULD be done is Root Overrides should be used, instead.

I've taken the liberty of looking into Steam AutoCloud documentation so I can tell you exactly what to do. You'll want to delete the current mac/linux "root paths" (I don't think this deletes data, but you might wanna test privately just to make sure), and instead add two Root Overrides. 

Give both of these the Original Root of WinAppDataRoaming, give one "Mac OS X" as its OS and "MacAppSupport" as its new root, and the other give "Linux + SteamOS" and "LinuxHome" for their respective root overrides. You can then give the Mac one the "Add/Replace Path" of "Godot/app_userdata/Beat Banger", and the Linux one ".local/share/godot/app_userdata/Beat Banger"
. This also solves the issue that the game currently syncs ALL Godot saves on Linux, not just the ones related to BB.

When all is said and done, the game should now sync between Windows, Mac and Linux! I'd love to hear back on this since cloud saves are important to me. If the issue is fixed or there's some other issue rendering this impossible, I'll be sure to close this issue. Thanks!

**Comment by komdog** [comment]
#30

**Comment by komdog** [comment]
We've disabled cloud saves for now, We might revisit them in the future but due to Incompatibilities with the older version of the game, we're currently shelving that

**Comment by ScottCarammell** [comment]
daaamn, that sucks. hope you get that sorted out
