### ISSUE TITLE
Beat Banger showing xbox buttons when I have ps4 controller connected

### ISSUE THREAD

**Issue by Lumpymoose09** [bunfan/beat-banger-public#379]
### Discord Tag

lumpymoose

### Issue Description

I have my ps4 controller connected but instead of showing ps4 buttons it shows xbox buttons, I'd be happy to know how to fix.

### OS

Windows

### Version

3.7

### Modifiers Enabled?

No modifers enabled

### What level or section is the scene present.

the whole game

**Comment by Stefan-Mitric** [comment]
You may have Steam Input enable that why it may change to Xbox. You can change the icons in the Settings.
![image](https://github.com/bunfan/beat-banger-public/assets/146543675/07a0fa04-1575-44e1-9c82-06f852188d2a)

**Comment by 1MPexe** [comment]
Is this issue still occurring?

**Comment by Stefan-Mitric** [comment]
It got fixed by the user.
