### ISSUE TITLE
Song Progress Bar. Ui hiding, fullscreen Visuals

### ISSUE THREAD

**Issue by SeerXela** [bunfan/beat-banger-public#38]
Hey so here are some of my suggested features that i think would honestly help improve the game:

1. Song Progress Bar
So this feature would probably be better for hands free mode but i think would also be useful for the normal mode too. So the basic idea would be a way to tell where you are in the song that could be anywhere on the screen during the song but i would suggest it is on the edge of the screen as a small bar that fills up, maybe even with timestamps for things like stages or animation changes or even the "climax" of the song, i have always found it useful to know where i am in the song so i know where in the song i am struggling or just to know where my ummm..."favorite parts" are at, this could even be a setting you can turn on or off based on your preference or even customized like size and color. For a  good reference, YouTube is a good example of what i am suggesting

Here is an example of the YouTube progress bar for reference:
![Song Progress bar](https://github.com/bunfan/beat-banger-public/assets/144551873/c1923eef-6825-45ad-a969-19fa27eb32a8)

2. Ui Hiding
Similar to the my previous suggestion i think this would be better for hands free mode. The idea for this one is that from my experience, especially with mods that have text, the ui hides a decent portion of the visuals, i find this can be a bit jarring and also unnecessary as i don't need to see the combo counter and lives in hands free, so they only serve as a way to block the visuals when i want to ummm..."enjoy" the visuals on screen, again this could even be a setting that can be turned on and off, but i personally don't see the need for the combo and lives during hands free mode at all.

Here is an example of the ui covering the visuals:
![Ui Hiding](https://github.com/bunfan/beat-banger-public/assets/144551873/08edcef6-22c5-47b1-bb34-857cd30dfcb4)

3. Fullscreen Visuals
I understand this will probably be the hardest to implement, especially as i don't have alot of knowledge in coding or game design. But even during mods i find that it's common that most of the screen is simply not being used, it remains very small in a portrait, i understand this might be simpler but it feels like a waste to see so much of the screen being underutilized, whether modding or in the main game. As a minor note, was also wondering if it would be possible to add some minor visual effects, just to make progress feel slightly more special and rewarding to do well or even just survive till the end of the song.

Here is an image showing the difference between a portrait view of a mod and a widescreen view of a mod:
![Portrait View Example](https://github.com/bunfan/beat-banger-public/assets/144551873/63ee52da-4db8-42cb-8252-9e807c6d4aaa)

**Comment by komdog** [comment]
UI hiding has been **implemented**, and the progress bar is **being worked on**, but unfortunately, I don't think we'll be able to change the game's resolution to fit portrait view mods from an older version.
