### ISSUE TITLE
v0.03:  Save Data potentially getting deleted

### ISSUE THREAD

**Issue by NV082292** [bunfan/beat-banger-public#38]
I've bumped into this issue a couple times just now and it seems like on occasion when starting up the game, i'm back to having all the other stages locked even though I completed them before.  I haven't really done or deleted anything that would have caused this to happen.  Perhaps something to do with the exit code?

**Comment by komdog** [comment]
Do you have a log you can upload? In the console type the command `viewlog` and then copy and paste the contents of that file here.

**Comment by komdog** [comment]
Should be fixed in 0.04
