### ISSUE TITLE
NOT A GAME BUG: Bunfan website has a wrong redirect on the Discord Button

### ISSUE THREAD

**Issue by Stefan-Mitric** [bunfan/beat-banger-public#381]
### Issue Description

It redirect to the Store instead to the Discord Server

![image](https://github.com/bunfan/beat-banger-public/assets/146543675/a366d5b3-d415-4451-bd45-2f76bc300426)

### OS

Windows

### Version

3.7

**Comment by komdog** [comment]
Fixed
