### ISSUE TITLE
Random Crashing

### ISSUE THREAD

**Issue by Autizmo21** [bunfan/beat-banger-public#382]
### Discord Tag

@cocknball.

### Issue Description

When ever i start playing Cathy or Zoe expert mode the game will randomly crash during the song with no inherent pattern.

### OS

Windows

### Version

3.7

### Modifiers Enabled?

none

### What level or section is the scene present.

Cathy and Zoe Expert mode

**Comment by Stefan-Mitric** [comment]
Duplicate #349
