### ISSUE TITLE
Key hit naming inconsistency

### ISSUE THREAD

**Issue by Odalys-Goathoof** [bunfan/beat-banger-public#39]
Despite being labeled as: Perfect, Great, Good and Miss (both in debug and above the bottom bar once hit), the results screen shows the qualities of hits as: Perfect, Good, OK and Miss.
This applies to both 64 and 32 versions of the game and, while a smaller bug, is quite visible.
![inconsistency](https://user-images.githubusercontent.com/84477455/120217521-bf65a980-c238-11eb-9d29-0f2e73195312.png)

**Comment by komdog** [comment]
Tweaking in v1.1
