### ISSUE TITLE
The Game Suddenly Crashes when you play in Expert (Steam version)

### ISSUE THREAD

**Issue by MorterAfeck** [bunfan/beat-banger-public#390]
### Discord Tag

Morter Afeck

### Issue Description

Every time I attemp to play the first level in Expert Difficulty, when I try ti beat it, the game crashes out of nowhere, usually been on the Blowjob section 3

### OS

Windows

### Version

3.7

### Modifiers Enabled?

Modifiers disable

### What level or section is the scene present.

Present in Cathy gameplay only (expert difficulty)

**Comment by Stefan-Mitric** [comment]
Duplicate #349
