### ISSUE TITLE
Stuck at theater (patreon branch)

### ISSUE THREAD

**Issue by Lucario-G7** [bunfan/beat-banger-public#399]
### Discord Tag

lucario_g7

### Issue Description

https://github.com/bunfan/beat-banger-public/assets/108599013/bd166cb7-ba84-49fc-8294-ee9bc136abcd

### OS

Windows

### Version

3.7

### Modifiers Enabled?

none

### What level or section is the scene present.

Theater

**Comment by Stefan-Mitric** [comment]
fixed in v38
