### ISSUE TITLE
DiFfErEnT CoLoRs

### ISSUE THREAD

**Issue by BitHeaven-Official** [bunfan/beat-banger-public#4]
**Describe the bug**
Color of buttons controller and color above buttons are different.

**To Reproduce**
1. Connect controller (any XInput (smth. like xbox one))
2. Run any level

**Expected behavior**
I expect same color, becoz different colors distracts attention.

**Screenshots**
A - blue, X - red and etc.
![image](https://github.com/bunfan/beat-banger-public/assets/33015545/5129f227-00d6-44ef-93bc-506dbcb49151)

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.1
 - Version v2.892

**Comment by komdog** [comment]
X-input gamepads are accounted for. If you're getting the wrong colors, that means something other than an X-input gamepad is being registered. 

The current color coding for X Input gamepads is
```gdscript
"XInput Gamepad": return [
	Color(0.42,0.96,0.22,1), #Green
	Color(0.99,0.11,0.11,1), #Red
	Color(0.1,0.37,1,1), #Blue
	Color(1,0.94,0.1,1), #Yellow
	Color(0.1,0.1,0.17,1), #Gray
	Color(0.1,0.1,0.17,1), #Gray
]
```


Could you copy and paste your most recent log file from `~/.local/share/godot/app_userdata/Beat Banger/logs` or a screenshot of your in-game logs by pressing the `F4` button.

**Comment by BitHeaven-Official** [comment]
![image](https://github.com/bunfan/beat-banger-public/assets/33015545/f297cef2-cbc7-4928-9bd9-3978d8636a49)
[beat_banger.log](https://github.com/bunfan/beat-banger-public/files/11660043/beat_banger.log)

**Comment by komdog** [comment]
This has been fixed and will be pushed soon
