### ISSUE TITLE
Playstation layout

### ISSUE THREAD

**Issue by Krisanfa** [bunfan/beat-banger-public#40]
**Well, hi for the one reading.**
_I am making this petition for someone adding a icon layout for the ones (like me) who play with an playstation controller. 
To of course enjoy more the gameplay, and having a more confident pressing buttons (?)_
![imagen_2023-09-21_204622714](https://github.com/bunfan/beat-banger-public/assets/145726597/2b438f26-4229-4356-a236-95a890474960)
Nothing more to ask, good day!

**Comment by komdog** [comment]
These buttons already exist; your steam client is likely overriding what type of controller the game thinks you're using. 

Try disabling steam input and restarting the game.
