### ISSUE TITLE
Exit to Title Screen Option Bug

### ISSUE THREAD

**Issue by patrick03524** [bunfan/beat-banger-public#404]
### Discord Tag

lance024

### Issue Description

The bug occurs when you click on the "return to title menu" option in a game, the keys stop working and although the game does not freeze this makes it impossible to do anything and only close it through the file manager. 

I want to mention that I haven't installed any mod to the game yet and I just completed the 4 songs available (Cathy, Zoe, Glare and Claire). 

Attached is a video with audio from Gale's gameplay showing that the keys stop working (However, it seems that the F2 key that opens the developer console is still working properly).

https://github.com/user-attachments/assets/07ba15af-9155-4205-a88b-b65dababfe38

### OS

Windows

### Version

3.7

### Modifiers Enabled?

No

### What level or section is the scene present.

Present in Cathy, Zoe, Glare and Claire gameplay

**Comment by Stefan-Mitric** [comment]
Fixed in version 24w28c
