### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by PapiStar0rigin** [bunfan/beat-banger-public#408]
### Issue Description

I bought the game yesterday and everything was fine. And now today when i launch it i first got a white screen for like 2-3 minutes and absolutely no sound, even with the sound at 100. So just by curiosity i decide to launch a music to see if the sound will magically come back. But instead the music was all glitchy, the button i had to press where either disappearing, being way too slow or even going towards me then going away.

### OS

Windows

### Version

3.7

### Modifiers Enabled?

No

### What level or section is the scene present.

Title menu and different level

**Comment by Kapioga** [comment]
Hi PapiStar,

Could you provide more information regarding this issue? Im not able to replicate the problem your having on several other devices. 

Thanks!
-Koga

**Comment by PapiStar0rigin** [comment]
Yeah about that... I completely forgot to send another message after.
 The problem was coming from my PC and after an update everything is fine
for now.

**Comment by Kapioga** [comment]
ok cool, glad it worked out!
Let us know if you need help with anything else!

-Koga
