### ISSUE TITLE
My game close randomly

### ISSUE THREAD

**Issue by Szinak11** [bunfan/beat-banger-public#411]
### Discord Tag

@szinak11

### Issue Description

i play whit a level and in the middle sometimes the game just close randomly this day my game closed like 10 times

### OS

Windows

### Version

3.7

### Modifiers Enabled?

i not used any mode

### What level or section is the scene present.

this happen whit me in every level even in mods too

**Comment by Szinak11** [comment]
in modifiers enabled?   i wanted say i not used any modifier sorry

**Comment by Stefan-Mitric** [comment]
Duplicate of #349
