### ISSUE TITLE
Mods not working right

### ISSUE THREAD

**Issue by Kampstir** [bunfan/beat-banger-public#42]
When I attempted to use a mod from the release version there was no mod folder but after creating one myself the mod loaded but there was no music and the notes were stuck in place, I don't know if the mods need to be updated or beat banger itself but I thought it would be good to know.

https://github.com/bunfan/beat-banger-public/assets/146936808/de7f1968-f04b-401b-b78c-9d686b5bdb15

**Comment by komdog** [comment]
This is most likely a problem with the mod, not the base game. You should contact the mod's creator if you want to find a solution.
