### ISSUE TITLE
itchio update mod bug

### ISSUE THREAD

**Issue by Cornbreadarts** [bunfan/beat-banger-public#43]
**Describe the bug**
so really big bug, after deleting and redownloading  my mods folder it let me play them, but once you beat them it just stays on the last frame and doesnt move on to the level ranking and completion. only way to get out is via the menu which means you effectively cant beat mods and unlock auto play for them
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Version [e.g. v2.88]
laptop: windows 11
**Additional context**
Problem is consistent on every mod not just certain omes

**Comment by komdog** [comment]
This is due to Godot 4 removing Webm support. We're working on a fix for this.

**Comment by komdog** [comment]
Moving to #59
