### ISSUE TITLE
Pause Menu doesn't work when Handsfree

### ISSUE THREAD

**Issue by Whatever-Guy** [bunfan/beat-banger-public#43]
**Description**
The Pause Menu doesn't work properly in mods (I haven't tried it in the official levels though) when using the handsfree mode.

**To Reproduce:**
**1.** Press **"/"** to open the console
**2.** Write _handsfree_ to activate autoplay
**3.** Open any mod level (or official level, but yet to be confirmed)
**4.** Press **Esc** to open the Pause Menu
**5.** Try accepting or cancelling anything with **Z** or **X**

**Expected behavior**
You can open and close it with **Esc** and navigate it, but can't select anything with **Z** or cancel with **X**

**Screenshots**
I have no screenshot, but I guess it's pretty clear.

**Additional context**
I'm no programmer, but I'm guessing it's because, when Auto-playing, the keys are deactivated, and they are not being activated when in the Pause Menu. If that's the problem, I'm guessing it will happen as well with the official levels.

**Comment by komdog** [comment]
**Could you attach your logs to this post?**
reproduce the bug, the go to the main menu console and type `viewlog` then paste those contents here.

**Comment by Whatever-Guy** [comment]
> **Could you attach your logs to this post?**
> reproduce the bug, the go to the main menu console and type `viewlog` then paste those contents here.

Huh, just tried to reproduce the bug and now it isn't working, I guess it was a one time thing or the game didn't load correctly because of my pc or something, but the pause menu worked now. Thanks anyways
