### ISSUE TITLE
Only Z keys before 5th beat

### ISSUE THREAD

**Issue by Odalys-Goathoof** [bunfan/beat-banger-public#44]
Beats 0 to 4 will always play the same keys, that being two Z presses on beat 0 and 4.
You cannot change said beats to null, X nor C presses.
Included screenshot shows C set to all beats 0-5, and the gameplay showing only C appear on beat 5 and up:
![image](https://user-images.githubusercontent.com/84477455/120610815-d8967200-c453-11eb-945c-110bb566494e.png)

**Comment by komdog** [comment]
This can be resolved by changing the starting note type on the chart.cfg file.
