### ISSUE TITLE
Level ending crash (MacOs)

### ISSUE THREAD

**Issue by pepertlo0212** [bunfan/beat-banger-public#44]
**Describe the bug**
Game crashes once the level ends, right before showing the stars earned. Both with base levels and mods.

**To Reproduce**

Game ver: 3.1.2 MacOs Build (from itch.io)

1. Just finish any level at any difficulty.

**Expected behavior**
Shows the stars and points earned and gives the option to return to the levels menu, or shows the level ending cutscene.

**Video**

https://drive.google.com/file/d/1dyPptb8SaYtLvADVhg3FcQn33m_Z2r4j/view?usp=sharing

**Desktop:**
 - OS: MacOs
 - Version: Sonoma 14.0
 - Device: MacBook Air M2, 2022

**Additional context**
Idk why, maybe MacOs not trusting the game, but in order for me to run it I had to run this command on the terminal once:
`xattr -d com.apple.quarantine /path/to/app.app`. Otherwise, it would say that the app is damaged and that I should put it in the bin.

`xattr -cr /path/to/app.app` also works for me.

**Comment by komdog** [comment]
This issue is a result of GPU particles not being supported on macOS 😭
This issue has been fixed and will be pushed next patch
