### ISSUE TITLE
Lovense IP/Port Input Non-functional

### ISSUE THREAD

**Issue by defcap** [bunfan/beat-banger-public#45]
**Describe the bug**
The IP and Port boxes for Lovense integration are non-editable in version v3.11000000000058

**To Reproduce**
1. Go to the Lovense Integration tab under options
2. Attempt to click on the IP or port boxes
3. Attempt fails, no other inputs are valid except v and x

**Expected behavior**
Click on the box and be able to enter the number.

**Screenshots**
![image](https://github.com/bunfan/beat-banger-public/assets/147297955/c43be8ef-f0bd-44a6-86bc-f66ca7545832)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version v3.11000000000058

**Additional context**
I can verify that this was working in previous builds.

**Comment by komdog** [comment]
This was due to a debug menu blocking all mouse input to control nodes. This issue has been fixed and will be pushed next patched
