### ISSUE TITLE
(MacOs) Xbox controller buttons not showing 

### ISSUE THREAD

**Issue by pepertlo0212** [bunfan/beat-banger-public#46]
**Describe the bug**
Connecting a Xbox Series controller, makes all the buttons show as blank/not showing at all, while still detecting presses. Connecting a PS4 controller works normally.

**To Reproduce**

Game ver: 3.1.2 MacOs Build (from itch.io)

1. Connect a Xbox Series Controller (via bluetooth or wired)
2. Launch the game (buttons to select and go back not showing)
3. Play a level (buttons showing as blank)

**Expected behavior**
Just as with the PS4 controller, shows the correct buttons for the Xbox layout.

**Video**

https://drive.google.com/file/d/1pvDGT8iOjetdfvWe5wmGfdsgxfEAWVOf/view?usp=share_link

**Desktop:**
 - OS: MacOs
 - Version: Sonoma 14.0
 - Device: MacBook Air M2, 2022

**Additional context**
Even though it is a bug, can't deny it would be a cool idea for some kind of "Super Expert" or "blind" mode, because you can still see the color but not the input needed.

**Comment by komdog** [comment]
We'll soon add the ability for users to set the custom glyphs they want
