### ISSUE TITLE
The ability to change the volume of music and sfx

### ISSUE THREAD

**Issue by b-cloud09** [bunfan/beat-banger-public#46]
I think the ability to change the volume of sfx and music would be a nice feature since it’ll allow more people to hear the actual “plap” sounds you’d actually hear in porno.

**Comment by komdog** [comment]
This feature already exists and is editable through the chart file. Unless you're talking about a UI element that does that

**Comment by b-cloud09** [comment]
Yes i mean a UI element. Or atleast something that’s always there in the menu.

**Comment by komdog** [comment]
Added in v2.0
