### ISSUE TITLE
can't progress past Cathy's level on v3.x

### ISSUE THREAD

**Issue by MontaGlek** [bunfan/beat-banger-public#49]
**Describe the bug**
Anytime i finish Cathy's level I dont receive any reward or do i get to go to the next stage. No cutscene or anything

Downloaded any 3.x Version
buy beggining shop modifers 
buy the 3 extra lives
play Cathy's level (Any diff, does not matter)
finish
See error
**Expected behavior**
To receive my reward and proceed to the next stage

**Screenshots**
https://bunkrr.su/v/PgydObSbhpK8W Video to the issue

**Desktop (please complete the following information):**
 - OS: WIN 10
 - all of v3

**Additional context**

**Comment by komdog** [comment]
I just patched it. It involved some wonky code when checking whether the level was beaten with cheats. Will push next update
