### ISSUE TITLE
less of a bug but...

### ISSUE THREAD

**Issue by familiarfan** [bunfan/beat-banger-public#5]
More of a grammatical inconsistency than anything but the n in notes should be capitalized in my opinion to fit the other options.
![Screenshot 2023-06-02 015240](https://github.com/bunfan/beat-banger-public/assets/135310287/64c0c69d-3183-4ae8-a9d6-ce5a6aaecd33)

**Comment by komdog** [comment]
Fixed in 2.893. Thank you for reporting. 💖

**Comment by familiarfan** [comment]
Thank you so much
