### ISSUE TITLE
Ability to see song title under map name

### ISSUE THREAD

**Issue by LiterallyJumble** [bunfan/beat-banger-public#50]
A small subtitle under the names of mod files when hovered over in game showing what song the mod is going to play, not exactly showing the ogg file name as that is not always accurate, but having the mod maker have to type in the name of the song, just like having to type in the name of the mod.

And maybe also add the ability to put the mod creators name there as well

Just a little example here, a little extra section comes down when the map is "Selected" showing the song name, mod maker name, and maybe a small preview of the song in the background

![Example](https://user-images.githubusercontent.com/83520510/121823202-fe8b0480-cce6-11eb-8576-c44306fca14a.png)

**Comment by komdog** [comment]
Will be released in next version
