### ISSUE TITLE
UI Overlay in Gallery

### ISSUE THREAD

**Issue by Stefan-Mitric** [bunfan/beat-banger-public#54]
You can see the low-tint dash that goes across the screen. It isn't like this on the Steam Version.

![Steam_Version_Overlay](https://github.com/bunfan/beat-banger-public/assets/146543675/0b474e35-2159-4e07-9924-5458f43233ff)
![Patreon_Build_Overlay](https://github.com/bunfan/beat-banger-public/assets/146543675/b14a81a6-1ea0-484f-bb3f-161ac27fb40b)

**Comment by komdog** [comment]
Removed tint in 3.14
