### ISSUE TITLE
ESC to exit menus and ESC bug

### ISSUE THREAD

**Issue by GitHubEnderman** [bunfan/beat-banger-public#58]
I'm requesting that the ESC key be made as an alternate way to go back in menus, just a small convenience feature as most games allow ESC to be used to go back to main menus and then close the game at the main menu.

I also noticed when opening the game it says "Press Z to Continue, Press ESC to Quit" but pressing ESC on this menu doesn't actually close the menu which may be a bug.

**Comment by komdog** [comment]
I fixed the issue in which the the ESC key doesn't work during the game's startup, However, the ESC key is used specifically for opening menus during the game, so It'd be weird to use it to navigate them. I'd probably do backspace instead.
