### ISSUE TITLE
Small Animation Bug in the Mods Menu

### ISSUE THREAD

**Issue by developerx-official** [bunfan/beat-banger-public#59]
**Describe the bug**
When leaving the mods menu with the back button, if pressed more than once, the exit animation plays on every keypress, and not the initial keypress.

**To Reproduce**
1. Go to the mods menu.
2. Press the back button (default x) several times, you will see the animation play for every button press until returning to the main menu.

**Expected behavior**
I expected the animation to play once, on the initial keypress, and not on the ones sequentially after.

**Comment by komdog** [comment]
Fixed in version 1.3
