### ISSUE TITLE
Progress Wiped after Update

### ISSUE THREAD

**Issue by JoeSchmoe81** [bunfan/beat-banger-public#6]
Sorry if I format this Wrong at all, I really am not super great with this type of thing. I installed the most recent update on steam, and when I entered the game, I had lost all my progress which was unfortunate as I had a good amount of in game currency saved up. and a 5 star performance or two. 

My Steps;
1. I clicked update on the game
2. I entered the game after the update finished
3. Felt sadness when I saw I had lost all my progress

Expected behavior:
I expected to have my progress, as previous times I had booted up the game, my progress was saved.

Desktop:
 - OS: Windows 10 Pro
 - Version 22H2
**Additional context**
I really enjoy this game, I really hope this doesn't happen every update, and I dread having to grind back up the progress I had lost. Either way I still love and support this game!

**Comment by komdog** [comment]
I don't think this bug is reproducible. Are you sure you didn't mess with any of the saved data or play any older versions of the game before updating?

**Comment by JoeSchmoe81** [comment]
About 60 percent certain. either way its no big deal, I just thought I should inform you.

**Comment by komdog** [comment]
The latest version of the game progress is saved in a much different manner, which means this will hard reset your progress only once, but should no longer be wiped when updating.
