### ISSUE TITLE
Bug: 'HotMenu' Label Incorrectly Alters on User Navigation Actions

### ISSUE THREAD

**Issue by Stefan-Mitric** [bunfan/beat-banger-public#63]
### What happened?

The label on the 'HotMenu' changes when a user selects an option and then presses the 'ESC' key, instead of using the 'Go Back' button. The label remains on the option that was selected, rather than reverting to its default state which is 'MENU'.

https://github.com/bunfan/beat-banger-public/assets/146543675/f8b3881b-1911-43c3-bf11-5de72033d233

### Version

3.1.5 (Beta)

**Comment by komdog** [comment]
Fixed in 3.16
