### ISSUE TITLE
Bug: Keybind Settings Menu Retains Focus on Previously Selected Key After Re-entry

### ISSUE THREAD

**Issue by Stefan-Mitric** [bunfan/beat-banger-public#64]
### What happened?

When navigating to the Keybinds settings, shifting to another key, pressing 'ESC' instead of the 'Go Back' button, and subsequently re-entering the Keybinds settings, the focus remains on the selected last key.

https://github.com/bunfan/beat-banger-public/assets/146543675/35e43f90-77a0-4448-b308-262a97e01b34

### Version

3.1.5 (Beta)

**Comment by komdog** [comment]
Fixed in 3.16
