### ISSUE TITLE
In-Game Custom Note Skins?

### ISSUE THREAD

**Issue by skywaave** [bunfan/beat-banger-public#65]
A case where there would be cosmetic note skins unlocked after each song that responds to the character you unlock them from would be pretty cool, and might give a bit of a sense of progression.

An example of a game that does this would be from the DJMAX series with their gears and note skins: [https://www.youtube.com/watch?v=BFfRQfWudaA](url)

**Comment by komdog** [comment]
This is a cool idea. Though in the future we'll probably give modders the ability to add custom note styles per level anyways. As of version 2.0 you can change the colors of the notes using the configuration files.
