### ISSUE TITLE
Visual Bug:  'No HUD' Modifier Fails to Disable HUD

### ISSUE THREAD

**Issue by Stefan-Mitric** [bunfan/beat-banger-public#66]
### What happened?

Enabling the 'No HUD' modifier before being in a level doesn't disable the HUD. However, it starts working again after entering the level and then deactivating and reactivating the modifier.

https://github.com/bunfan/beat-banger-public/assets/146543675/320ecd24-fd71-442a-b81b-a01ade9902cd

### Version

3.1.5 (Beta)

**Comment by komdog** [comment]
Fixed in 3.16
