### ISSUE TITLE
Show input bar in handsfree mode

### ISSUE THREAD

**Issue by 2shoess** [bunfan/beat-banger-public#70]
**What feature would you like to request?:**
A toggle or option to show the beat inputs during handsfree mode like in older versions. Or just restore visibility and let us hide it with the bar_position line.

**Additional context**
Hiding the inputs during handsfree is nice but its also very helpful to be able to playtest in handsfree mode and be able to see the inputs without having to actually play the level every time

**Comment by komdog** [comment]
Added ability to show and hide HUD by typing `hud` in the console on the main menu.
