### ISSUE TITLE
Bug: Lag Spikes

### ISSUE THREAD

**Issue by Sha-Le-Wo** [bunfan/beat-banger-public#71]
### Discord Tag

shalewo

### What happened?

The only bugs I had were on the first song it was a little low quality, and on the newest song I had 1 or 2 lag spikes. There is a high chance this was just my computer but I am just making sure. Also it turned out great in my opinion.

### Version

3.165 (Secret)

**Comment by Stefan-Mitric** [comment]
I have a question regarding the bug report you mentioned, specifically the "first song" and "newest song" in the GitHub project I observed. Are you referring to different levels or the selection of records?
