### ISSUE TITLE
Insane Scroll

### ISSUE THREAD

**Issue by theGrames** [bunfan/beat-banger-public#71]
When browsing mods, and only mods, the selection speed with the arrow keys is insane fast.

- Open Game
- Go to Mods
- _Try_ to hover a mod you want

I expected to scroll one by one with the arrow keys.

https://streamable.com/8eaph0

Note: I am tapping the arrow keys lightly on the mod screen. No holding. 
Seen is me scrolling on the menu fine, but the mod menu absolutely goes ham. Play menu is also fine but that isn't shown.

Thank you for all your hard work also, Beat Banger rocks.

**Comment by theGrames** [comment]
Found an unofficial fix: Capping the framerate for the engine/BeatBanger fixes it, through NVIDIA Control Panel for example.

**Comment by teh404guy** [comment]
A better fix is to seperate the mods menu's logic from the fps abit or use godot equivalent of delta Time
