### ISSUE TITLE
Bug: Completing Cathy level on expert difficulty caused the title to crash

### ISSUE THREAD

**Issue by FnooxiOwO** [bunfan/beat-banger-public#72]
### Discord Tag

FnooxiOwO

### What happened?

After completing Cathy level on expert difficulty the title crashed to the desktop when pressed "continue" on the summary screen. The issue occurred only once (repro 1/5) and the progress was not lost. Completing the Cathy level on lower difficulties did not cause any crashes. It might be occurring on the fresh installs when played for the first time. 

### Version

3.165 (Secret)

**Comment by Stefan-Mitric** [comment]
Claire Level Crashing #84
