### ISSUE TITLE
Can't open the game at all

### ISSUE THREAD

**Issue by CoolHipster678** [bunfan/beat-banger-public#72]
I downloaded the latest version of the game (v 1.311) from the itch.io page
and made a folder on my desktop to put the game in (It's Italian btw)

I click on the .exe file and wait for it, but nothing happens

What do I have to do?

![Screenshot (661)](https://user-images.githubusercontent.com/87997095/127033247-f26fca3d-728e-43b3-97f4-b87d3c779b35.png)

**Comment by komdog** [comment]
It's probably your antivirus software or windows defender. Either way there's nothing I can do about your client side security.
