### ISSUE TITLE
Bug: Dev overlay appears after mashing buttons

### ISSUE THREAD

**Issue by DionOfSpice** [bunfan/beat-banger-public#73]
### Discord Tag

@dionofspice

### What happened?

I was pressing left and right buttons in rapid succession while in gallery and this appeared (see attached screenshot). I managed to close and open it once again by repeating the button-mashing process. Not sure what exact button combination is causing this (or if it's intentional). I'm using an xbox 360 controller.

edit: after some trial and error. the exact combination ended up being RIGHT RIGHT LEFT LEFT RIGHT RIGHT. it works in any menu, not just gallery.

![Screenshot 2023-10-22 074353](https://github.com/bunfan/beat-banger-public/assets/134839215/2858167b-84b8-40f8-86c2-ebd892790354)

### Version

3.165 (Secret)

**Comment by komdog** [comment]
I made this harder
