### ISSUE TITLE
Cum fx in gallery mode for mods not working properly.

### ISSUE THREAD

**Issue by Rippl2** [bunfan/beat-banger-public#76]
Whenever you get to the cum loop while in gallery mode of a mod, the cum fx aren't placed properly and end up off-screen.

Here are some videos of the cum fx glitching (nsfw obviously stupid):

SIDENOTE: The Judy vid contains the loops of the demo version of beat banger and not 1.311

https://user-images.githubusercontent.com/46795336/127751929-d2056939-b8aa-43fa-870b-063220a0ef62.mp4

https://user-images.githubusercontent.com/46795336/127751967-43fc54cc-ef9b-4238-a0f1-088dd10a4bc4.mp4

https://user-images.githubusercontent.com/46795336/127751996-862e97f8-7d7f-4e09-ab7f-ddcb9f89c71f.mp4

https://user-images.githubusercontent.com/46795336/127752039-e455b697-ede0-4acb-9918-84e446045711.mp4

**Comment by theGrames** [comment]
This is less of a bug and more of an outdated chart. This issue resides because of the implementation of `last_transition`. `cum_fx` are only broken on charts that lack `last_transiton` and instead have a final normal transition.
