### ISSUE TITLE
Bug: Cutscene Crash (Gale)

### ISSUE THREAD

**Issue by JackMoon19** [bunfan/beat-banger-public#76]
### Discord Tag

@joaquinluna18

### What happened?

The game crashed when I skipped the ending cutscene for Gale's level. 

### Version

3.165 (Secret)

### Relevant log output

```shell
It may have been because I skipped it too fast.
```

**Comment by Stefan-Mitric** [comment]
Claire Level Crashing #84

**Comment by komdog** [comment]
Dupe of fixed issue #84
