### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by razzldazzlrose** [bunfan/beat-banger-public#78]
### Discord Tag

@razzldazzlrose (or cherrybomb!! my username and my nickname respectively)

### What happened?

opened up the mod menu and, for some reason, doing so opened up a debug mode of some sort? showed a whole bunch of text about things in-game loading and various binary options, couldn't interact with anything and leaving the mod menu didn't make it disappear (might've fat-fingered a button in that menu? it didn't pop up the moment i went into mods, but it's hard to determine that kinda stuff)

### Version

3.165 (Secret)

**Comment by komdog** [comment]
Fixed #74
