### ISSUE TITLE
Adjustable Offset

### ISSUE THREAD

**Issue by ghj0sh** [bunfan/beat-banger-public#79]
**What feature would you like to request?:**
I'd like for there to be an adjustable offset.  Maybe some value or slider in the options menu.  Helps people keep the charts on time for people that have latency with audio.

**Additional context**
I noticed that there's a note offset for the maps in the cfg file, but the note offset isn't in sync for me.  Changed it to 0 and had no issues with the charts being off time.  I assume that would be the audio offset for the song and not the actual note offset.  Not too sure how you programmed it.

**Comment by komdog** [comment]
That already exists. In the chart file you can change a `note_offset` value to tweak the positions of the spawn notes
