### ISSUE TITLE
Moving the Controller analog stick (Xbox One Controller) on stage select screen makes the selector go crazy

### ISSUE THREAD

**Issue by Shadowking58** [bunfan/beat-banger-public#8]
Moving the Controller analog stick (Xbox One Controller) on stage select screen makes the selector go crazy

**To Reproduce**
Plug in Xbox One Controller, go to stage select, use analog stick. The analog stick doesn't work in in the mod stage select menu

**Expected behavior**
Goes from left to right.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Version [e.g. v2.88]

**Additional context**

https://github.com/bunfan/beat-banger-public/assets/25795865/98994ca7-058b-4677-9c79-26d1189a01e2

**Comment by komdog** [comment]
The issue has been resolved for now by turning off the joystick. This will probably be re-enabled later once I can stabilize it.
