### ISSUE TITLE
Bug: Mod Webms Don't Run

### ISSUE THREAD

**Issue by 0TAKO** [bunfan/beat-banger-public#81]
### Discord Tag

0TAKO

### What happened?

I've tried to play some mods and sometimes they black out for an instant several times and then continue with the mod.
Other mods like the demo levels you can´t end them beacause they frose at the end (This only happens in the cathy level of tihis mod).
Also the mods get cut off at the end.

### OS

Windows

### Version

3.165 (Secret)

**Comment by komdog** [comment]
I'm not sure about the blacking-out thing, but mods from 2.x versions of Beat Banger have type `WEBM` videos as ending scenes. Godot 4 has removed support for this, and mods will have to convert their videos to `.ogv` until we implement a workaround

**Comment by komdog** [comment]
We've implemented a webm conversion script in 3.21
