### ISSUE TITLE
Bug: Controller icons colored improperly on Linux 

### ISSUE THREAD

**Issue by ScottCarammell** [bunfan/beat-banger-public#83]
### Discord Tag

ScottCarammell

### What happened?

As the title says, controller icons on the Linux build appear to be discolored, colored more like the keyboard icons, which makes the game harder than it needs to be since I've gotten so used to pressing by color rather than letter. I have screenshots showing the issue, but I'm not sure how to send them through Github. I doubt they'd be useful anyway for such a self-explanatory issue, though if you do need them for whatever reason, my Discord is attached. 

I've played the pre-release on Windows, it doesn't appear to be an issue on there.

### OS

Steam Deck (Linux)

### Version

3.165 (Secret)

**Comment by komdog** [comment]
I can't help unless I can see what the problem is. Try taking a picture with a smartphone.

**Comment by ScottCarammell** [comment]
Sorry, I figured out how to do it. As you asked,

![20231022114213_1](https://github.com/bunfan/beat-banger-public/assets/66961806/4a698836-c684-4164-950d-e9260b05d446)
![20231022114216_1](https://github.com/bunfan/beat-banger-public/assets/66961806/86677c2d-a0bd-4ace-8921-dd437e05efce)
![20231022114240_1](https://github.com/bunfan/beat-banger-public/assets/66961806/5ec349f8-d117-4dc1-91a4-2134b2703d44)

**Comment by komdog** [comment]
This is intended. These are Steamdeck glyphs.
