### ISSUE TITLE
Random Level Crashing

### ISSUE THREAD

**Issue by Stefan-Mitric** [bunfan/beat-banger-public#84]
### What happened?

The game unexpectedly closes without any visibility in the debug or log.

[beatbanger.log](https://github.com/bunfan/beat-banger-public/files/13063899/beatbanger.log)

https://github.com/bunfan/beat-banger-public/assets/146543675/8d533c43-9c82-4592-b30b-0960dd150513

### OS

Windows

### Version

3.165 (Secret)

**Comment by DoodleSurf** [comment]
@Stefan-Mitric for how long did you play this current session?

**Comment by Stefan-Mitric** [comment]
So i cleared my save file closed the game then played it from Cathy to Claire, and then the bug appeared.

**Comment by Stefan-Mitric** [comment]
I found out what was causing the bug. When you finish a level, wait long enough, and then press continue, it closes the game. The Unlock pop-up could be causing this issue, or one specific audio file can't find the path mentioned in the log file.
[Possible Issue. zip](https://github.com/bunfan/beat-banger-public/files/13064551/Possible.Issue.zip)
[beatbanger. log](https://github.com/bunfan/beat-banger-public/files/13064556/beatbanger.log)

**Comment by DoodleSurf** [comment]
Its still inconsistent, its not tied to the amb.ogg loading issue, nor the user input.
@Stefan-Mitric can you launch the game with `--verbose` and send a log upon crash?

**Comment by Stefan-Mitric** [comment]
That is the log file that i sent after the crash.

**Comment by DoodleSurf** [comment]
with `--verbose` flag?

**Comment by Stefan-Mitric** [comment]
yes

**Comment by DoodleSurf** [comment]
Managed to get the crash on steam release too but the trigger for it is still inconsistent, crashed after closing the score screen
Could possibly be fixed by implementing the safer child node removal [!33](https://gitlab.bunfan.com/bunfan/games/beat-banger/-/merge_requests/33)
[bb_crash.log](https://github.com/bunfan/beat-banger-public/files/13064623/bb_crash.log)

**Comment by komdog** [comment]
Hopefully Fixed in 3.2

**Comment by komdog** [comment]
Reopening incase new crash cases are this same issue

**Comment by DoodleSurf** [comment]
@Stefan-Mitric can you check on the crash? In 3.31 there has been implement a patch to try an alleviate this issue

**Comment by Stefan-Mitric** [comment]
It's still happening.

**Comment by Stefan-Mitric** [comment]
After several attempts, it does not appear anymore.
