### ISSUE TITLE
Bug: Menu Music Overlap 

### ISSUE THREAD

**Issue by SaddoBoi** [bunfan/beat-banger-public#88]
### Discord Tag

@SadBoiOnline

### What happened?

While running mods the main menu music persists through the mod level it may be related to selecting a new menu theme from the EXTRAS tab
[BB Bug Report.zip](https://github.com/bunfan/beat-banger-public/files/13064178/BB.Bug.Report.zip)

### OS

Windows

### Version

3.165 (Secret)

**Comment by komdog** [comment]
Fixed in 3.21
