### ISSUE TITLE
Crackly Audio Glitch

### ISSUE THREAD

**Issue by Flatsodadrinker** [bunfan/beat-banger-public#89]
### Discord Tag

flatsodadrinker

### What happened?

 The Secret game version seems to have an odd glitch that is corrupting the audio making it crackly and break up. This happened shortly after beating the Cathy level on expert.

### OS

Windows

### Version

3.165 (Secret)

### Relevant log output

```shell
no log
```

**Comment by Stefan-Mitric** [comment]
Could you please create a video for us? It would greatly help in better understanding the process and validating the results. Thank you!

**Comment by Flatsodadrinker** [comment]
I cannot seem to get the game to re do the bug but I had it happen twice I think it only happened when I didn't miss a beat but I didn't miss one when trying to record but it wouldn't do it. But the bug would happen right after the finishing scene and it wasn't just locked to Cathy it also happened on Claire's level. Once the score would come onto screen the audio would crackle and pop I'm sure it wasn't my headphone because I then opened a video to test my audio and it wasn't being affected while the game was. Sorry that I can't get a video of it.

**Comment by DoodleSurf** [comment]
@Flatsodadrinker which audio hardware are you using? Some headphones provide multiple chat/game audio switch where the chat channel is usually set to mono and lower quality - which can make the engine go wonky once system decides to use it as and output playback channel.

**Comment by Flatsodadrinker** [comment]
Corsair headphone with ICUE audio hardware

**Comment by DoodleSurf** [comment]
Which the model?

**Comment by DoodleSurf** [comment]
@Flatsodadrinker can you please specify the exact model of your headphones?

**Comment by Flatsodadrinker** [comment]
Void Elite Wireless

**Comment by DoodleSurf** [comment]
Make sure the headphones aren't set to mono or low Hz frequency in Windows Control Panel Sound Setting, iCue, Realtek or any third party audio suite like Sonic Suite.

**Comment by Stefan-Mitric** [comment]
@Flatsodadrinker has the situation improved, or has the issue recurred?

**Comment by Flatsodadrinker** [comment]
It seems to have fixed when the full update came out so I'm unsure what caused it/fixed it

**Comment by Stefan-Mitric** [comment]
Got fixed.
