### ISSUE TITLE
Replay mode/Gallery

### ISSUE THREAD

**Issue by HarajukuBun** [bunfan/beat-banger-public#9]
One thing you should totally do is when you finish a level, the scenes you saw could be replayed in like some kind of replay mode/gallery ! so you don't have to play the level again to see the animations again and literally have your eyes more focused on the beats-

**Comment by Slingx54** [comment]
I agree. The game is nice, but some of us would like to focus on the art. Would be nice to focus on it without the flashing lights or time limit of a song length.

Or maybe make the gallery files Patreon exclusive. I myself subscribed after the game's release, hoping they'd be there.
