### ISSUE TITLE
Bug: Mods not working

### ISSUE THREAD

**Issue by JackMoon19** [bunfan/beat-banger-public#91]
### Discord Tag

@joaquinluna18

### What happened?

Some of my mods aren't working. When I go into a mod level the notes don't appear but the song continues. I have noticed it is mostly the ones without difficulty selection.

### OS

Windows

### Version

3.165 (Secret)

**Comment by Stefan-Mitric** [comment]
Could you please create a video for us? It would greatly help in better understanding the process and validating the results. Thank you!

**Comment by JackMoon19** [comment]
Sorry I can't seem to recreates the mod bug. I think I some how fixed it by unistalling and reinstalling the mod
