### ISSUE TITLE
Bug: Selecting difficulty in Modded Levels results in always playing the lowest difficulty

### ISSUE THREAD

**Issue by defcap** [bunfan/beat-banger-public#92]
### Discord Tag

eloquentlobotomy

### What happened?

I have selected harder difficulties in multiple mods, including one that I made, and the game always plays the easiest chart (First chart in the notes array). If I had to speculate, I would say that when the buttons were iteratively created according to the amount of charts, the variable used for selecting the difficulty from the gui was left static, i.e. always 1. That's just a rough guess though.
The notes show up properly when shuffled to the beginning of the list, and the notes files that I checked are laid out in the same fashion that the story level notes files are.

### OS

Windows

### Version

3.15 (Beta)

**Comment by komdog** [comment]
Fixed in 3.21
