### ISSUE TITLE
animation Bug: finish scene

### ISSUE THREAD

**Issue by Splatspot** [bunfan/beat-banger-public#95]
### Discord Tag

@Splatspot

### What happened?

you can see the final "vid" loop at the end of cathys level

### OS

Windows

### Version

3.165 (Secret)

**Comment by Stefan-Mitric** [comment]
Does it loop forever?
Could you please create a video for us? It would greatly help in better understanding the process and validating the results. Thank you!

**Comment by komdog** [comment]
Duplicate of bug #80
