### ISSUE TITLE
Bug: Early sketches for later scenes left in the files

### ISSUE THREAD

**Issue by BraixenFan** [bunfan/beat-banger-public#96]
### Discord Tag

@BraixenFan

### What happened?

I went to look into the files and there's a filled folder for Dawna, including her cutscene, level, script and even music. As well as the post-level cutscene for claire. I assume these are placeholders that patreons may see early, but you might not want to leave them in for the release

### OS

Windows

### Version

3.165 (Secret)

**Comment by komdog** [comment]
This isn't a bug
