### ISSUE TITLE
Custom background textures/patterns from some mods won't load in 1.311

### ISSUE THREAD

**Issue by TrueHiddenS** [bunfan/beat-banger-public#99]
In version 1.311, the game for some older mods won't read what's in the Textures folder leaving the background patterns for some mods to be set to default. Said folder is still able to be read for some mods in version 1.1 of the game. I used the Vaporeon mod in both versions 1.1 and 1.311 to showcase this bug and have attached screenshots below.

Version 1.1 
![image](https://user-images.githubusercontent.com/90650272/133154708-90e0c6e4-a26e-4177-b862-487e9b9a8cc4.png)

Version 1.311 
![image](https://user-images.githubusercontent.com/90650272/133154543-fe569689-04de-4098-8fdd-e13698589618.png)

**Comment by jarreclel** [comment]
Are mods ready to play?

**Comment by TrueHiddenS** [comment]
They are, I looked into this issue weeks afterwards in my own time, it turns out 1.1 and 1.311 read the CFG file differently as there are different commands that change how it reads the folders depending on which version the mod is playing on. Older mods' CFG files are structured differently compared to recent ones.

**Comment by theGrames** [comment]
@TrueHiddenS is correct. Following the new 1.3 format corrects how backgrounds are displayed.
https://github.com/bunfan/beat-banger-public/wiki/Chart-Formatting-1.3
